# Different Choices for Indexing

In [1]:
import pandas as pd
import numpy as np

In [2]:
ser = pd.Series(range(5), index=list("abcde"))
ser.loc[["a", "c", "e"]]

a    0
c    2
e    4
dtype: int64

In [3]:
df = pd.DataFrame(np.arange(25).reshape(5, 5), index=list("abcde"), columns=list("abcde"))
df.loc[["a", "c", "e"], ["b", "d"]]

    b   d
a   1   3
c  11  13
e  21  23

# Basics

In [4]:
dates = pd.date_range("1/1/2000", periods=8)
df = pd.DataFrame(
    np.random.randn(8, 4),
    index=dates,
    columns=["A", "B", "C", "D"],
)

In [5]:
df

                   A         B         C         D
2000-01-01  0.034626 -1.270831 -0.172811 -0.325400
2000-01-02  0.006262  1.125683 -2.309653 -0.235443
2000-01-03 -0.047427  0.515866 -1.343650 -0.792758
2000-01-04  0.569808 -0.052967 -1.444916 -0.814285
2000-01-05 -1.069808  1.445569  0.480677 -0.265840
2000-01-06  0.046709 -0.217452 -0.143423  0.087556
2000-01-07  0.556351 -0.503087  0.954005 -0.365380
2000-01-08 -0.047738  0.463129 -0.457330 -0.557410

In [6]:
# Indexing with [] on a DataFrame returns the column values as a Series
s = df["A"]

# Indexing with [] on a Series returns a scalar
s[dates[5]]

np.float64(0.04670876586072946)

In [7]:
# Exchange values between columns A and B
df[["B", "A"]] = df[["A", "B"]]
df

                   A         B         C         D
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400
2000-01-02  1.125683  0.006262 -2.309653 -0.235443
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758
2000-01-04 -0.052967  0.569808 -1.444916 -0.814285
2000-01-05  1.445569 -1.069808  0.480677 -0.265840
2000-01-06 -0.217452  0.046709 -0.143423  0.087556
2000-01-07 -0.503087  0.556351  0.954005 -0.365380
2000-01-08  0.463129 -0.047738 -0.457330 -0.557410

In [8]:
# WARNING: Using .loc always aligns the AXES. So, trying to make a
#          transform with .loc will fail because column alignment
#          happens before value assignment!
df[["A", "B"]]

                   A         B
2000-01-01 -1.270831  0.034626
2000-01-02  1.125683  0.006262
2000-01-03  0.515866 -0.047427
2000-01-04 -0.052967  0.569808
2000-01-05  1.445569 -1.069808
2000-01-06 -0.217452  0.046709
2000-01-07 -0.503087  0.556351
2000-01-08  0.463129 -0.047738

In [9]:
df.loc[:, ["B", "A"]] = df[["A", "B"]]
df[["A", "B"]]

                   A         B
2000-01-01 -1.270831  0.034626
2000-01-02  1.125683  0.006262
2000-01-03  0.515866 -0.047427
2000-01-04 -0.052967  0.569808
2000-01-05  1.445569 -1.069808
2000-01-06 -0.217452  0.046709
2000-01-07 -0.503087  0.556351
2000-01-08  0.463129 -0.047738

In [10]:
# To swap column values with .loc, use raw values
df.loc[:, ["B", "A"]] = df[["A", "B"]].to_numpy()
df[["A", "B"]]

                   A         B
2000-01-01  0.034626 -1.270831
2000-01-02  0.006262  1.125683
2000-01-03 -0.047427  0.515866
2000-01-04  0.569808 -0.052967
2000-01-05 -1.069808  1.445569
2000-01-06  0.046709 -0.217452
2000-01-07  0.556351 -0.503087
2000-01-08 -0.047738  0.463129

In [11]:
# NOTE: When using .iloc pandas DOES NOT align axes so
#       the following will swap the columns
df[["A", "B"]]

                   A         B
2000-01-01  0.034626 -1.270831
2000-01-02  0.006262  1.125683
2000-01-03 -0.047427  0.515866
2000-01-04  0.569808 -0.052967
2000-01-05 -1.069808  1.445569
2000-01-06  0.046709 -0.217452
2000-01-07  0.556351 -0.503087
2000-01-08 -0.047738  0.463129

In [12]:
df.iloc[:, [1, 0]] = df[["A", "B"]]
df[["A", "B"]]

                   A         B
2000-01-01 -1.270831  0.034626
2000-01-02  1.125683  0.006262
2000-01-03  0.515866 -0.047427
2000-01-04 -0.052967  0.569808
2000-01-05  1.445569 -1.069808
2000-01-06 -0.217452  0.046709
2000-01-07 -0.503087  0.556351
2000-01-08  0.463129 -0.047738

# Attribute Access

In [13]:
sa = pd.Series([1, 2, 3], index=list("abc"))
dfa = df.copy()

In [14]:
sa.b

np.int64(2)

In [15]:
dfa.A

2000-01-01   -1.270831
2000-01-02    1.125683
2000-01-03    0.515866
2000-01-04   -0.052967
2000-01-05    1.445569
2000-01-06   -0.217452
2000-01-07   -0.503087
2000-01-08    0.463129
Freq: D, Name: A, dtype: float64

In [16]:
sa.a = 5
sa

a    5
b    2
c    3
dtype: int64

In [17]:
dfa.A = list(range(len(dfa.index)))
dfa

            A         B         C         D
2000-01-01  0  0.034626 -0.172811 -0.325400
2000-01-02  1  0.006262 -2.309653 -0.235443
2000-01-03  2 -0.047427 -1.343650 -0.792758
2000-01-04  3  0.569808 -1.444916 -0.814285
2000-01-05  4 -1.069808  0.480677 -0.265840
2000-01-06  5  0.046709 -0.143423  0.087556
2000-01-07  6  0.556351  0.954005 -0.365380
2000-01-08  7 -0.047738 -0.457330 -0.557410

In [18]:
# To create a new column, use the indexing with brackets
dfa["A"] = list(range(len(dfa.index)))
dfa

            A         B         C         D
2000-01-01  0  0.034626 -0.172811 -0.325400
2000-01-02  1  0.006262 -2.309653 -0.235443
2000-01-03  2 -0.047427 -1.343650 -0.792758
2000-01-04  3  0.569808 -1.444916 -0.814285
2000-01-05  4 -1.069808  0.480677 -0.265840
2000-01-06  5  0.046709 -0.143423  0.087556
2000-01-07  6  0.556351  0.954005 -0.365380
2000-01-08  7 -0.047738 -0.457330 -0.557410

In [19]:
# Assign a dict to a row of a DataFrame
x = pd.DataFrame({"x": [1, 2, 3], "y": [3, 4, 5]})
x.iloc[1] = {"x": 9, "y": 99}
x

   x   y
0  1   3
1  9  99
2  3   5

# Slicing Ranges

In [20]:
# A Series
s

2000-01-01    0.034626
2000-01-02    0.006262
2000-01-03   -0.047427
2000-01-04    0.569808
2000-01-05   -1.069808
2000-01-06    0.046709
2000-01-07    0.556351
2000-01-08   -0.047738
Freq: D, Name: A, dtype: float64

In [21]:
# Slicing a Series returns a slice of the values, and the corresponding indices
s[:5]

2000-01-01    0.034626
2000-01-02    0.006262
2000-01-03   -0.047427
2000-01-04    0.569808
2000-01-05   -1.069808
Freq: D, Name: A, dtype: float64

In [22]:
# with a step of 2
s[::2]

2000-01-01    0.034626
2000-01-03   -0.047427
2000-01-05   -1.069808
2000-01-07    0.556351
Freq: 2D, Name: A, dtype: float64

In [23]:
# step = -1 i.e. backwards
s[::-1]

2000-01-08   -0.047738
2000-01-07    0.556351
2000-01-06    0.046709
2000-01-05   -1.069808
2000-01-04    0.569808
2000-01-03   -0.047427
2000-01-02    0.006262
2000-01-01    0.034626
Freq: -1D, Name: A, dtype: float64

In [24]:
# Use [] for setting as well
s2 = s.copy()
s2[:5] = 0
s2

2000-01-01    0.000000
2000-01-02    0.000000
2000-01-03    0.000000
2000-01-04    0.000000
2000-01-05    0.000000
2000-01-06    0.046709
2000-01-07    0.556351
2000-01-08   -0.047738
Freq: D, Name: A, dtype: float64

In [25]:
df[:3]

                   A         B         C         D
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400
2000-01-02  1.125683  0.006262 -2.309653 -0.235443
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758

In [26]:
df[:3]

                   A         B         C         D
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400
2000-01-02  1.125683  0.006262 -2.309653 -0.235443
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758

In [27]:
df[::-1]

                   A         B         C         D
2000-01-08  0.463129 -0.047738 -0.457330 -0.557410
2000-01-07 -0.503087  0.556351  0.954005 -0.365380
2000-01-06 -0.217452  0.046709 -0.143423  0.087556
2000-01-05  1.445569 -1.069808  0.480677 -0.265840
2000-01-04 -0.052967  0.569808 -1.444916 -0.814285
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758
2000-01-02  1.125683  0.006262 -2.309653 -0.235443
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400

# Selection by Label

In [28]:
# .loc is the primary label-based indexing method
s1 = pd.Series(np.random.randn(6), index=list("abcdef"))
s1

a   -0.077085
b   -0.034129
c    0.565520
d   -1.268560
e    0.026700
f    0.908501
dtype: float64

In [29]:
s1.loc["c":]

c    0.565520
d   -1.268560
e    0.026700
f    0.908501
dtype: float64

In [30]:
s1.loc["b"]

np.float64(-0.034129346305570185)

In [31]:
# also used for setting values
s1.loc["c":] = 0
s1

a   -0.077085
b   -0.034129
c    0.000000
d    0.000000
e    0.000000
f    0.000000
dtype: float64

In [32]:
df1 = pd.DataFrame(
    np.random.randn(6, 4),
    index=list("abcdef"),
    columns=list("ABCD"),
)
df1

          A         B         C         D
a  1.407482  0.991806 -0.958254 -0.603504
b -0.906954  0.705600  0.416845  0.542520
c -0.757033 -0.097435  0.393580 -0.213658
d -0.402449 -0.938015  0.618543  3.602028
e -1.425115  0.480775  0.746272  1.466596
f -1.174423 -1.180872  0.568094 -0.060676

In [33]:
df1.loc[["a", "b", "d"], :]

          A         B         C         D
a  1.407482  0.991806 -0.958254 -0.603504
b -0.906954  0.705600  0.416845  0.542520
d -0.402449 -0.938015  0.618543  3.602028

In [34]:
df1.loc["d":, "A":"C"]

          A         B         C
d -0.402449 -0.938015  0.618543
e -1.425115  0.480775  0.746272
f -1.174423 -1.180872  0.568094

In [35]:
df1.loc["a"]

A    1.407482
B    0.991806
C   -0.958254
D   -0.603504
Name: a, dtype: float64

In [36]:
# Get values with a Boolean array
df1.loc["a"] > 0

A     True
B     True
C    False
D    False
Name: a, dtype: bool

In [37]:
df1.loc[:, df1.loc["a"] > 0]

          A         B
a  1.407482  0.991806
b -0.906954  0.705600
c -0.757033 -0.097435
d -0.402449 -0.938015
e -1.425115  0.480775
f -1.174423 -1.180872

In [38]:
# NA values in a Boolean array propagate as False
mask = pd.array([True, False, True, False, pd.NA, False], dtype="boolean")
mask

<BooleanArray>
[True, False, True, False, <NA>, False]
Length: 6, dtype: boolean

In [39]:
df1[mask]

          A         B         C         D
a  1.407482  0.991806 -0.958254 -0.603504
c -0.757033 -0.097435  0.393580 -0.213658

In [40]:
# getting a value explicitly: row a, column A
df1.loc["a", "A"]

np.float64(1.407481877050903)

## Slicing with Labels

In [41]:
s = pd.Series(list("abcde"), index=[0, 3, 2, 5, 4])
s

0    a
3    b
2    c
5    d
4    e
dtype: object

In [42]:
s.loc[3:5]

3    b
2    c
5    d
dtype: object

In [43]:
# return a new Series sorted by labels
s.sort_index()

0    a
2    c
3    b
4    e
5    d
dtype: object

In [44]:
s.sort_index().loc[1:6]

2    c
3    b
4    e
5    d
dtype: object

In [45]:
s = pd.Series(list("abcdef"), index=[0, 3, 2, 5, 4, 2])
s

0    a
3    b
2    c
5    d
4    e
2    f
dtype: object

In [46]:
s.loc[3:5]

3    b
2    c
5    d
dtype: object

# Selection by Position
##### Integer-based indexing - lower bound included/upper bound excluded

In [47]:
s1 = pd.Series(np.random.randn(5), index=list(range(0, 10, 2)))
s1

0   -0.898240
2    0.343084
4    0.442650
6    0.949990
8   -1.813636
dtype: float64

In [48]:
s1.iloc[:3]

0   -0.898240
2    0.343084
4    0.442650
dtype: float64

In [49]:
s1.iloc[3]

np.float64(0.9499897492942759)

In [50]:
s1.iloc[:3] = 0
s1

0    0.000000
2    0.000000
4    0.000000
6    0.949990
8   -1.813636
dtype: float64

In [51]:
df1 = pd.DataFrame(
    np.random.randn(6, 4),
    index=list(range(0, 12, 2)),
    columns=list(range(0, 8, 2)),
)
df1

           0         2         4         6
0  -0.992181  1.040009  0.200675  0.423755
2  -0.951026  0.787492  0.081328  0.125911
4   0.619612 -0.046247 -1.471689 -0.164382
6   0.316646  0.503483 -0.296257 -0.461539
8  -1.019089  0.527188 -0.512653  0.042838
10  0.390479  0.687639 -0.404283  0.833079

In [52]:
# Select via integer slicing
df1.iloc[:3]

          0         2         4         6
0 -0.992181  1.040009  0.200675  0.423755
2 -0.951026  0.787492  0.081328  0.125911
4  0.619612 -0.046247 -1.471689 -0.164382

In [53]:
df1.iloc[1:5, 2:4]

          4         6
2  0.081328  0.125911
4 -1.471689 -0.164382
6 -0.296257 -0.461539
8 -0.512653  0.042838

In [54]:
# Select using integer list
df1.iloc[[1, 3, 5], [1, 3]]

           2         6
2   0.787492  0.125911
6   0.503483 -0.461539
10  0.687639  0.833079

In [55]:
df1.iloc[1:3, :]

          0         2         4         6
2 -0.951026  0.787492  0.081328  0.125911
4  0.619612 -0.046247 -1.471689 -0.164382

In [56]:
df1.iloc[:, 1:3]

           2         4
0   1.040009  0.200675
2   0.787492  0.081328
4  -0.046247 -1.471689
6   0.503483 -0.296257
8   0.527188 -0.512653
10  0.687639 -0.404283

In [57]:
df1.iloc[1, 1]

np.float64(0.7874922214830766)

In [58]:
df1.iloc[1]

0   -0.951026
2    0.787492
4    0.081328
6    0.125911
Name: 2, dtype: float64

In [59]:
# Out of range slice indexes
x = list("abcdef")
x

['a', 'b', 'c', 'd', 'e', 'f']

In [60]:
x[4:10]

['e', 'f']

In [61]:
x[8:10]

[]

In [62]:
s = pd.Series(x)
s

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [63]:
s.iloc[4:10]

4    e
5    f
dtype: object

In [64]:
dfl = pd.DataFrame(np.random.randn(5, 2), columns=list("AB"))
dfl

          A         B
0 -0.135572  0.625332
1  0.079202 -0.068838
2 -2.090408  1.038934
3  0.857501  0.114984
4 -0.014442 -0.430973

In [65]:
# This slice goes out of bounds (there's no column with index 2)->empty DataFrame returned
dfl.iloc[:, 2:3]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [66]:
dfl.iloc[:, 1:3]

          B
0  0.625332
1 -0.068838
2  1.038934
3  0.114984
4 -0.430973

# Selection by Callable

In [67]:
df1 = pd.DataFrame(
    np.random.randn(6, 4),
    index=list("abcdef"),
    columns=list("ABCD"),
)
df1

          A         B         C         D
a -0.685111 -1.126545 -1.905369 -1.582427
b -0.745208 -1.386930  0.522608  1.134732
c  0.652048  0.285667 -0.419933 -1.217358
d  0.337378  0.565721  0.085901  0.718668
e -0.137792  1.053879  0.068922  1.880088
f -1.108719 -1.018593 -2.613226  0.358377

In [68]:
# Select rows where column A is +ve; select all columns
df1.loc[lambda df: df["A"] > 0, :]

          A         B         C         D
c  0.652048  0.285667 -0.419933 -1.217358
d  0.337378  0.565721  0.085901  0.718668

In [69]:
df1.loc[:, lambda df: ["A", "B"]]

          A         B
a -0.685111 -1.126545
b -0.745208 -1.386930
c  0.652048  0.285667
d  0.337378  0.565721
e -0.137792  1.053879
f -1.108719 -1.018593

In [70]:
df1.iloc[:, lambda df: [0, 1]]

          A         B
a -0.685111 -1.126545
b -0.745208 -1.386930
c  0.652048  0.285667
d  0.337378  0.565721
e -0.137792  1.053879
f -1.108719 -1.018593

In [71]:
# Callable indexing in Series
df1["A"].loc[lambda s: s > 0]

c    0.652048
d    0.337378
Name: A, dtype: float64

In [72]:
# Chain data selection operations, without using a temp variable
bb = pd.read_csv("data/baseball.csv", index_col="id")

(bb.groupby(["year", "team"]).sum(numeric_only=True).loc[lambda df: df["r"] > 100])

           rownames  stint    g    ab    r    h  X2b  X3b  hr    rbi    sb  \
year team
1872 BL1        645      4  120   566  131  157   13    6   1   75.0   6.0
1873 BL1        708      2  106   511  147  170   18    8   2   80.0   4.0
     BS1        741      2  117   590  158  219   34    9   1  114.0  10.0
     NY2       1074      3  141   642  110  165   15    7   1   63.0   4.0
     PH1        656      2  103   496  104  182   16    8   0   69.0   1.0
...             ...    ...  ...   ...  ...  ...  ...  ...  ..    ...   ...
2007 LAN     715256     11  413  1021  153  293   61    3  36  154.0   7.0
     NYN    1073198     13  622  1854  240  509  101    3  61  243.0  22.0
     SFN     447198      5  482  1305  198  337   67    6  40  171.0  26.0
     TEX     178804      2  198   729  115  200   40    4  28  115.0  21.0
     TOR     357561      4  459  1408  187  378   96    2  58  223.0   4.0

            cs   bb     so   ibb   hbp    sh    sf  gidp
year team
1872 BL1   2.0    8    3.0   0.0   0.0   0.0   0.0   0.0
1873 BL1   1.0   12    3.0   0.0   0.0   0.0   0.0   0.0
     BS1   4.0   14    3.0   0.0   0.0   0.0   0.0   0.0
     NY2   1.0   15    5.0   0.0   0.0   0.0   0.0   0.0
     PH1   5.0    7    3.0   0.0   0.0   0.0   0.0   0.0
...        ...  ...    ...   ...   ...   ...   ...   ...
2007 LAN   5.0  114  141.0   8.0   9.0   3.0   8.0  29.0
     NYN   4.0  174  310.0  24.0  23.0  18.0  15.0  48.0
     SFN   7.0  235  188.0  51.0   8.0  16.0   6.0  41.0
     TEX   4.0   73  140.0   4.0   5.0   2.0   8.0  16.0
     TOR   2.0  190  265.0  16.0  12.0   4.0  16.0  38.0

[2175 rows x 19 columns]

# Combining Positional & Label-based Indexing

In [73]:
dfd = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]}, index=list("abc"))
dfd

   A  B
a  1  4
b  2  5
c  3  6

In [74]:
dfd.loc[dfd.index[[0, 2]], "A"]

a    1
c    3
Name: A, dtype: int64

In [75]:
dfd.iloc[[0, 2], dfd.columns.get_loc("A")]

a    1
c    3
Name: A, dtype: int64

## Reindexing

In [76]:
s = pd.Series([1, 2, 3])
s.reindex([1, 2, 3])

1    2.0
2    3.0
3    NaN
dtype: float64

In [77]:
# select only valid keys
labels = [1, 2, 3]
s.loc[s.index.intersection(labels)]

1    2
2    3
dtype: int64

In [78]:
# Intersect the desired labels with the current axis, and then reindex
s.loc[s.index.intersection(labels)].reindex(labels)

1    2.0
2    3.0
3    NaN
dtype: float64

# Selecting Random Samples

In [79]:
s = pd.Series([0, 1, 2, 3, 4, 5])

# If no arguments passed, returns 1 row
s.sample()

2    2
dtype: int64

In [80]:
# Can specify either a number of rows
s.sample(n=3)

1    1
4    4
5    5
dtype: int64

In [81]:
# or a fraction of the rows
s.sample(frac=0.5)

0    0
1    1
2    2
dtype: int64

In [82]:
# Sample with replacement
s = pd.Series([0, 1, 2, 3, 4, 5])

# Without replacement - the default
s.sample(n=6, replace=False)

1    1
4    4
3    3
2    2
5    5
0    0
dtype: int64

In [83]:
# with replacement
s.sample(n=6, replace=True)

1    1
1    1
3    3
1    1
0    0
5    5
dtype: int64

In [84]:
# If you want rows to have different probabilities of being selected,
# pass the sampling function sampling weights.
s = pd.Series([0, 1, 2, 3, 4, 5])
example_weight = [0, 0, 0.2, 0.2, 0.2, 0.4]
s.sample(n=3, replace=False, weights=example_weight)

5    5
4    4
3    3
dtype: int64

In [85]:
# weights will be re-normalized automatically
example_weight2 = [0.5, 0, 0, 0, 0, 0]
s.sample(n=1, replace=False, weights=example_weight2)

0    0
dtype: int64

In [86]:
# When using a DataFrame, pass as a string the name of the column with the weights
df2 = pd.DataFrame({"col1": [9, 8, 7, 6], "weight_column": [0.5, 0.4, 0.1, 0]})

df2.sample(n=3, weights="weight_column")

   col1  weight_column
1     8            0.4
0     9            0.5
2     7            0.1

In [87]:
# Can also sample columns instead of rows
df3 = pd.DataFrame({"col1": [1, 2, 3], "col2": [2, 3, 4]})

df3.sample(n=1, axis=1)

   col1
0     1
1     2
2     3

In [88]:
df4 = pd.DataFrame({"col1": [1, 2, 3], "col2": [2, 3, 4]})

# With a given seed, the sample will always draw the same rows
df4.sample(n=2, random_state=2)

   col1  col2
2     3     4
1     2     3

# Setting with Enlargement

In [89]:
se = pd.Series([1, 2, 3])
se

0    1
1    2
2    3
dtype: int64

In [90]:
# Setting a non-existent key in a Series, results in appending the new value
se[5] = 5
se

0    1
1    2
2    3
5    5
dtype: int64

In [91]:
dfi = pd.DataFrame(np.arange(6).reshape(3, 2), columns=["A", "B"])
dfi

   A  B
0  0  1
1  2  3
2  4  5

In [92]:
# Setting a non-existent key on a DataFrame, adds a new column
dfi.loc[:, "C"] = dfi.loc[:, "A"]
dfi

   A  B  C
0  0  1  0
1  2  3  2
2  4  5  4

In [93]:
# Setting a non-existent index label
dfi.loc[3] = 5
dfi

   A  B  C
0  0  1  0
1  2  3  2
2  4  5  4
3  5  5  5

# Fast Scalar Value Getting and Setting

In [94]:
s

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [95]:
# To access a singular scalar value use:
#       at      label-based scalar lookup
#       iat     integer-based scalar lookup
s.iat[5]

np.int64(5)

In [96]:
df

                   A         B         C         D
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400
2000-01-02  1.125683  0.006262 -2.309653 -0.235443
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758
2000-01-04 -0.052967  0.569808 -1.444916 -0.814285
2000-01-05  1.445569 -1.069808  0.480677 -0.265840
2000-01-06 -0.217452  0.046709 -0.143423  0.087556
2000-01-07 -0.503087  0.556351  0.954005 -0.365380
2000-01-08  0.463129 -0.047738 -0.457330 -0.557410

In [97]:
df.at[dates[5], "A"]

np.float64(-0.21745206643487416)

In [98]:
df.iat[3, 0]

np.float64(-0.052967421882331014)

In [99]:
# Can also set values. Since column E is missing in df
# the result is object enlargement
df.at[dates[5], "E"] = 7

In [100]:
df.iat[3, 0] = 7

# Boolean Indexing

In [101]:
s = pd.Series(range(-3, 4))
s

0   -3
1   -2
2   -1
3    0
4    1
5    2
6    3
dtype: int64

In [102]:
s[s > 0]

4    1
5    2
6    3
dtype: int64

In [103]:
s[(s < -1) | (s > 0.5)]

0   -3
1   -2
4    1
5    2
6    3
dtype: int64

In [104]:
s[~(s < 0)]

3    0
4    1
5    2
6    3
dtype: int64

In [105]:
df

                   A         B         C         D    E
2000-01-01 -1.270831  0.034626 -0.172811 -0.325400  NaN
2000-01-02  1.125683  0.006262 -2.309653 -0.235443  NaN
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758  NaN
2000-01-04  7.000000  0.569808 -1.444916 -0.814285  NaN
2000-01-05  1.445569 -1.069808  0.480677 -0.265840  NaN
2000-01-06 -0.217452  0.046709 -0.143423  0.087556  7.0
2000-01-07 -0.503087  0.556351  0.954005 -0.365380  NaN
2000-01-08  0.463129 -0.047738 -0.457330 -0.557410  NaN

In [106]:
df[df["A"] > 0]

                   A         B         C         D   E
2000-01-02  1.125683  0.006262 -2.309653 -0.235443 NaN
2000-01-03  0.515866 -0.047427 -1.343650 -0.792758 NaN
2000-01-04  7.000000  0.569808 -1.444916 -0.814285 NaN
2000-01-05  1.445569 -1.069808  0.480677 -0.265840 NaN
2000-01-08  0.463129 -0.047738 -0.457330 -0.557410 NaN

In [107]:
df2 = pd.DataFrame(
    {
        "a": ["one", "one", "two", "three", "two", "one", "six"],
        "b": ["x", "y", "y", "x", "y", "x", "x"],
        "c": np.random.randn(7),
    }
)
df2

       a  b         c
0    one  x  1.297922
1    one  y  2.245296
2    two  y -0.983071
3  three  x -0.576658
4    two  y -2.206855
5    one  x -1.058486
6    six  x  1.693202

In [108]:
# only want "two" or "three"
criterion = df2["a"].map(lambda x: x.startswith("t"))
df2[criterion]

       a  b         c
2    two  y -0.983071
3  three  x -0.576658
4    two  y -2.206855

In [109]:
# multiple criteria
df2[criterion & (df2["b"] == "x")]

       a  b         c
3  three  x -0.576658

# Indexing with isin

In [110]:
s = pd.Series(np.arange(5), index=np.arange(5)[::-1], dtype="int64")
s

4    0
3    1
2    2
1    3
0    4
dtype: int64

In [111]:
s.isin([2, 4, 6])

4    False
3    False
2     True
1    False
0     True
dtype: bool

In [112]:
s[s.isin([2, 4, 6])]

2    2
0    4
dtype: int64

In [113]:
s[s.index.isin([2, 4, 6])]

4    0
2    2
dtype: int64

In [114]:
s_mi = pd.Series(
    np.arange(6),
    index=pd.MultiIndex.from_product(
        [[0, 1], ["a", "b", "c"]],
    ),
)
s_mi

0  a    0
   b    1
   c    2
1  a    3
   b    4
   c    5
dtype: int64

In [115]:
# MultiIndex allows selecting a separate level to use in membership checkin:
s_mi.iloc[s_mi.index.isin([(1, "a"), (2, "b"), (0, "c")])]

0  c    2
1  a    3
dtype: int64

In [116]:
s_mi.iloc[s_mi.index.isin(["a", "c", "e"], level=1)]

0  a    0
   c    2
1  a    3
   c    5
dtype: int64

In [117]:
df = pd.DataFrame(
    {
        "vals": [1, 2, 3, 4],
        "ids": ["a", "b", "f", "n"],
        "ids2": ["a", "n", "c", "n"],
    }
)
values = ["a", "b", 1, 3]
df.isin(values)

    vals    ids   ids2
0   True   True   True
1  False   True  False
2   True  False  False
3  False  False  False

In [118]:
# Match values with certain columns
values = {"ids": ["a", "b"], "vals": [1, 3]}
df.isin(values)

    vals    ids   ids2
0   True   True  False
1  False   True  False
2   True  False  False
3  False  False  False

In [119]:
# Return the masked df where the values are not in the original
~df.isin(values)

    vals    ids  ids2
0  False  False  True
1   True  False  True
2  False   True  True
3   True   True  True

In [120]:
# Select a subset (a row) where each column must meet its own criterion
values = {"ids": ["a", "b"], "ids2": ["a", "c"], "vals": [1, 3]}
row_mask = df.isin(values).all(1)
df[row_mask]

   vals ids ids2
0     1   a    a

# The where() Method and Masking

In [121]:
s

4    0
3    1
2    2
1    3
0    4
dtype: int64

In [122]:
# Return only the selected rows
s[s > 0]

3    1
2    2
1    3
0    4
dtype: int64

In [123]:
# Return a Series of the same shape as the original
s.where(s > 0)

4    NaN
3    1.0
2    2.0
1    3.0
0    4.0
dtype: float64

In [124]:
dates = pd.date_range("1/1/2000", periods=8)
df = pd.DataFrame(
    np.random.randn(8, 4),
    index=dates,
    columns=list("ABCD"),
)
df[df < 0]  # Same as df.where(df < 0)

                   A         B         C         D
2000-01-01       NaN       NaN -1.551892 -1.433008
2000-01-02       NaN -1.098970 -0.580655 -0.800679
2000-01-03       NaN -0.089623       NaN -0.758091
2000-01-04 -0.531959 -2.241179 -2.130902 -0.393717
2000-01-05       NaN       NaN       NaN -0.034593
2000-01-06 -0.047992       NaN -0.479732       NaN
2000-01-07       NaN       NaN -1.342799       NaN
2000-01-08       NaN -0.697327 -1.219546       NaN

In [125]:
# To replace values where the condition is False:
df.where(df < 0, -df)

                   A         B         C         D
2000-01-01 -0.627846 -0.571119 -1.551892 -1.433008
2000-01-02 -0.524016 -1.098970 -0.580655 -0.800679
2000-01-03 -1.167411 -0.089623 -0.600193 -0.758091
2000-01-04 -0.531959 -2.241179 -2.130902 -0.393717
2000-01-05 -1.640721 -1.441594 -1.430755 -0.034593
2000-01-06 -0.047992 -0.175904 -0.479732 -0.539851
2000-01-07 -1.576929 -0.683424 -1.342799 -0.455422
2000-01-08 -0.097571 -0.697327 -1.219546 -0.369878

In [126]:
# Set values based on some Boolean criteria
s2 = s.copy()
s2[s2 > 0] = 0
s2

4    0
3    0
2    0
1    0
0    0
dtype: int64

In [127]:
df2 = df.copy()
df2[df2 < 0] = 0
df2

                   A         B         C         D
2000-01-01  0.627846  0.571119  0.000000  0.000000
2000-01-02  0.524016  0.000000  0.000000  0.000000
2000-01-03  1.167411  0.000000  0.600193  0.000000
2000-01-04  0.000000  0.000000  0.000000  0.000000
2000-01-05  1.640721  1.441594  1.430755  0.000000
2000-01-06  0.000000  0.175904  0.000000  0.539851
2000-01-07  1.576929  0.683424  0.000000  0.455422
2000-01-08  0.097571  0.000000  0.000000  0.369878

### Alignment

In [128]:
df2 = df.copy()
df2[df2[1:4] > 0] = 3
df2

                   A         B         C         D
2000-01-01  0.627846  0.571119 -1.551892 -1.433008
2000-01-02  3.000000 -1.098970 -0.580655 -0.800679
2000-01-03  3.000000 -0.089623  3.000000 -0.758091
2000-01-04 -0.531959 -2.241179 -2.130902 -0.393717
2000-01-05  1.640721  1.441594  1.430755 -0.034593
2000-01-06 -0.047992  0.175904 -0.479732  0.539851
2000-01-07  1.576929  0.683424 -1.342799  0.455422
2000-01-08  0.097571 -0.697327 -1.219546  0.369878

In [129]:
df2 = df.copy()
df2.where(df2 > 0, df2["A"], axis="index")

                   A         B         C         D
2000-01-01  0.627846  0.571119  0.627846  0.627846
2000-01-02  0.524016  0.524016  0.524016  0.524016
2000-01-03  1.167411  1.167411  0.600193  1.167411
2000-01-04 -0.531959 -0.531959 -0.531959 -0.531959
2000-01-05  1.640721  1.441594  1.430755  1.640721
2000-01-06 -0.047992  0.175904 -0.047992  0.539851
2000-01-07  1.576929  0.683424  1.576929  0.455422
2000-01-08  0.097571  0.097571  0.097571  0.369878

In [130]:
# Equivalent to:
df2 = df.copy()
df.apply(lambda x, y: x.where(x > 0, y), y=df["A"])

                   A         B         C         D
2000-01-01  0.627846  0.571119  0.627846  0.627846
2000-01-02  0.524016  0.524016  0.524016  0.524016
2000-01-03  1.167411  1.167411  0.600193  1.167411
2000-01-04 -0.531959 -0.531959 -0.531959 -0.531959
2000-01-05  1.640721  1.441594  1.430755  1.640721
2000-01-06 -0.047992  0.175904 -0.047992  0.539851
2000-01-07  1.576929  0.683424  1.576929  0.455422
2000-01-08  0.097571  0.097571  0.097571  0.369878

# Setting with Enlargement Conditionally Using numpy()

In [131]:
df = pd.DataFrame(
    {
        "col1": list("ABBC"),
        "col2": list("ZZXY"),
    }
)

# Set a new column color to "green" when the second column has "Z"
df["color"] = np.where(df["col2"] == "Z", "green", "red")
df

  col1 col2  color
0    A    Z  green
1    B    Z  green
2    B    X    red
3    C    Y    red

In [132]:
# For multiple conditions, use np.select()
conditions = [
    (df["col2"] == "Z") & (df["col1"] == "A"),
    (df["col2"] == "Z") & (df["col1"] == "B"),
    (df["col1"] == "B"),
]

choices = ["yellow", "blue", "purple"]
df["color"] = np.select(conditions, choices, default="black")
df

  col1 col2   color
0    A    Z  yellow
1    B    Z    blue
2    B    X  purple
3    C    Y   black

# The query() Method

In [133]:
n = 10
df = pd.DataFrame(np.random.randn(n, 3), columns=list("abc"))
df

          a         b         c
0  0.100438 -0.347704 -0.466190
1 -0.493562 -0.213976  0.167179
2 -0.215432  1.322057  1.268297
3  2.040689  0.966808 -0.669299
4 -2.692582 -1.875244  0.178885
5 -1.108034 -0.586597 -0.344396
6  0.300770 -0.654885 -0.874492
7  0.780281 -0.272076  0.177711
8  0.878301 -0.042438  0.564903
9  0.846267 -0.251818  0.162298

In [134]:
# Using pure Python
df[(df["a"] < df["b"]) & (df["b"] < df["c"])]

          a         b         c
1 -0.493562 -0.213976  0.167179
4 -2.692582 -1.875244  0.178885
5 -1.108034 -0.586597 -0.344396

In [135]:
# Using query
df.query("(a < b) & (b < c)")

          a         b         c
1 -0.493562 -0.213976  0.167179
4 -2.692582 -1.875244  0.178885
5 -1.108034 -0.586597 -0.344396

In [136]:
# Fall back on a named index if there's no column with the name "a"
df = pd.DataFrame(np.random.randint(n / 2, size=(n, 2)), columns=list("bc"))
df.index.name = "a"
df

   b  c
a
0  4  0
1  3  1
2  1  1
3  3  1
4  2  4
5  0  0
6  2  4
7  0  4
8  2  4
9  3  2

In [137]:
df.query("a < b and b < c")

Empty DataFrame
Columns: [b, c]
Index: []

In [138]:
# Use the word "index", if the index has no name.
df = pd.DataFrame(np.random.randint(n / 2, size=(n, 2)), columns=list("bc"))
df

   b  c
0  3  4
1  3  4
2  1  2
3  4  0
4  0  0
5  0  1
6  1  3
7  2  2
8  3  2
9  4  4

In [139]:
df.query("index < b and b < c")

   b  c
0  3  4
1  3  4

## MultiIndex query() Syntax

In [140]:
n = 10

colors = np.random.choice(["red", "green"], size=n)
foods = np.random.choice(["eggs", "ham"], size=n)

index = pd.MultiIndex.from_arrays([colors, foods], names=["color", "food"])
df = pd.DataFrame(np.random.randn(n, 2), index=index)
df

                   0         1
color food
green eggs  1.307775  0.230136
red   ham  -0.234883 -0.904713
green ham  -0.157016  0.178778
red   ham  -0.541093  0.582536
      eggs -1.028374 -0.090294
green ham   1.499122 -1.477680
      ham  -1.907400 -0.238996
      eggs -3.210047 -0.924562
red   ham   0.698835 -0.487702
      ham  -0.994993  0.071628

In [141]:
df.query("color == 'red'")

                   0         1
color food
red   ham  -0.234883 -0.904713
      ham  -0.541093  0.582536
      eggs -1.028374 -0.090294
      ham   0.698835 -0.487702
      ham  -0.994993  0.071628

In [142]:
# If the levels of the MultiIndex are unnamed
df.index.names = [None, None]
df

                   0         1
green eggs  1.307775  0.230136
red   ham  -0.234883 -0.904713
green ham  -0.157016  0.178778
red   ham  -0.541093  0.582536
      eggs -1.028374 -0.090294
green ham   1.499122 -1.477680
      ham  -1.907400 -0.238996
      eggs -3.210047 -0.924562
red   ham   0.698835 -0.487702
      ham  -0.994993  0.071628

In [143]:
df.query("ilevel_0 == 'red'")

                 0         1
red ham  -0.234883 -0.904713
    ham  -0.541093  0.582536
    eggs -1.028374 -0.090294
    ham   0.698835 -0.487702
    ham  -0.994993  0.071628

## query() Use Cases

In [144]:
df = pd.DataFrame(np.random.randn(n, 3), columns=list("abc"))
df2 = pd.DataFrame(np.random.randn(n + 2, 3), columns=df.columns)

expr = "0.0 <= a <= c <= 0.5"
map(lambda frame: frame.query(expr), [df, df2])

## query() Python versus pandas Syntax Comparison

In [145]:
df = pd.DataFrame(np.random.randint(n, size=(n, 3)), columns=list("abc"))
df

   a  b  c
0  8  4  3
1  0  0  9
2  5  1  2
3  5  7  9
4  2  9  9
5  8  7  6
6  7  0  1
7  4  4  2
8  0  7  5
9  0  7  5

In [146]:
# Alternatives with the same end result:
# (a < b) & (a < c)
# (a < b) and (a < c)
# a < b and b < c
df.query("a < b < c")  # pandas syntax

   a  b  c
3  5  7  9

In [147]:
df[(df["a"] < df["b"]) & (df["b"] < df["c"])]  # Python syntax

   a  b  c
3  5  7  9

## The <span style="color:#f06292">in</span> and <span style="color:#f06292">not in</span> operators

In [148]:
df = pd.DataFrame(
    {
        "a": list("aabbccddeeff"),
        "b": list("aaaabbbbcccc"),
        "c": np.random.randint(5, size=12),
        "d": np.random.randint(9, size=12),
    }
)
df

    a  b  c  d
0   a  a  2  2
1   a  a  3  6
2   b  a  4  8
3   b  a  0  5
4   c  b  0  2
5   c  b  4  8
6   d  b  2  6
7   d  b  2  7
8   e  c  0  7
9   e  c  2  5
10  f  c  2  1
11  f  c  2  5

In [149]:
df.query("a in b")

   a  b  c  d
0  a  a  2  2
1  a  a  3  6
2  b  a  4  8
3  b  a  0  5
4  c  b  0  2
5  c  b  4  8

In [150]:
# in pure Python the same would be
df[df["a"].isin(df["b"])]

   a  b  c  d
0  a  a  2  2
1  a  a  3  6
2  b  a  4  8
3  b  a  0  5
4  c  b  0  2
5  c  b  4  8

In [151]:
df.query("a not in b")

    a  b  c  d
6   d  b  2  6
7   d  b  2  7
8   e  c  0  7
9   e  c  2  5
10  f  c  2  1
11  f  c  2  5

In [152]:
# in pure Python
df[~df["a"].isin(df["b"])]

    a  b  c  d
6   d  b  2  6
7   d  b  2  7
8   e  c  0  7
9   e  c  2  5
10  f  c  2  1
11  f  c  2  5

In [153]:
df.query("a in b and c < d")

   a  b  c  d
1  a  a  3  6
2  b  a  4  8
3  b  a  0  5
4  c  b  0  2
5  c  b  4  8

In [154]:
# in pure Python
df[df["a"].isin(df["b"]) & (df["c"] < df["d"])]

   a  b  c  d
1  a  a  3  6
2  b  a  4  8
3  b  a  0  5
4  c  b  0  2
5  c  b  4  8

## Special use of the <span style="color:#f06292">==</span> operator with <span style="color:#f06292">list</span> objects

In [155]:
# Using == against a list is similar to using in/not in
df.query("b == ['a', 'b', 'c']")

    a  b  c  d
0   a  a  2  2
1   a  a  3  6
2   b  a  4  8
3   b  a  0  5
4   c  b  0  2
5   c  b  4  8
6   d  b  2  6
7   d  b  2  7
8   e  c  0  7
9   e  c  2  5
10  f  c  2  1
11  f  c  2  5

## Boolean Operators

In [156]:
# not/~ negates a boolean expression
df = pd.DataFrame(np.random.randn(n, 3), columns=list("abc"))
df["bools"] = np.random.randn(len(df)) > 0.5
df.query("~bools")

          a         b         c  bools
0  1.935855  1.696812  1.419111  False
1 -0.600989  0.719839  1.841420  False
2  0.203513  1.188567  0.844531  False
3  0.478237  0.605673  0.639008  False
5 -0.183623 -0.364397  0.921414  False
6  0.256706 -0.275553 -0.341331  False

In [157]:
df.query("not bools")

          a         b         c  bools
0  1.935855  1.696812  1.419111  False
1 -0.600989  0.719839  1.841420  False
2  0.203513  1.188567  0.844531  False
3  0.478237  0.605673  0.639008  False
5 -0.183623 -0.364397  0.921414  False
6  0.256706 -0.275553 -0.341331  False

In [158]:
df.query("not bools") == df[~df["bools"]]

      a     b     c  bools
0  True  True  True   True
1  True  True  True   True
2  True  True  True   True
3  True  True  True   True
5  True  True  True   True
6  True  True  True   True

In [159]:
# Short query syntax
shorter = df.query("a < b < c and (not bools) or bools > 2")
shorter

          a         b         c  bools
1 -0.600989  0.719839  1.841420  False
3  0.478237  0.605673  0.639008  False

In [160]:
# In pure Python
longer = df[(df["a"] < df["b"]) & (df["b"] < df["c"]) & (~df["bools"]) | (df["bools"] > 2)]
longer

          a         b         c  bools
1 -0.600989  0.719839  1.841420  False
3  0.478237  0.605673  0.639008  False

In [161]:
shorter == longer

      a     b     c  bools
1  True  True  True   True
3  True  True  True   True

# Duplicate data

In [162]:
# To remove duplicate rows, use duplicated and drop_duplicates.
# Provide as arguments the columns to use to identify duplicated rows.
#
# By default, the first row in a duplicate set is considered unique(retained).
# Use keep to specify whether to keep the first, last or drop ALL duplicates.
df2 = pd.DataFrame(
    {
        "a": ["one", "one", "two", "two", "two", "three", "four"],
        "b": ["x", "y", "x", "y", "x", "x", "x"],
        "c": np.random.randn(7),
    }
)
df2

       a  b         c
0    one  x  1.055873
1    one  y  0.849900
2    two  x -0.764668
3    two  y -0.034392
4    two  x  0.090410
5  three  x  0.504917
6   four  x -0.424608

In [163]:
# Return a Boolean Series indicating the duplicates.
# Use column "a" to identify duplicate rows
df2.duplicated("a")

0    False
1     True
2    False
3     True
4     True
5    False
6    False
dtype: bool

In [164]:
df2.duplicated("a", keep="last")

0     True
1    False
2     True
3     True
4    False
5    False
6    False
dtype: bool

In [165]:
df2.duplicated("a", keep=False)

0     True
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [166]:
df2.drop_duplicates("a")

       a  b         c
0    one  x  1.055873
2    two  x -0.764668
5  three  x  0.504917
6   four  x -0.424608

In [167]:
df2.drop_duplicates("a", keep="last")

       a  b         c
1    one  y  0.849900
4    two  x  0.090410
5  three  x  0.504917
6   four  x -0.424608

In [168]:
df2.drop_duplicates("a", keep=False)

       a  b         c
5  three  x  0.504917
6   four  x -0.424608

In [169]:
df2.duplicated(["a", "b"])

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [170]:
df2.drop_duplicates(["a", "b"])

       a  b         c
0    one  x  1.055873
1    one  y  0.849900
2    two  x -0.764668
3    two  y -0.034392
5  three  x  0.504917
6   four  x -0.424608

In [171]:
df3 = pd.DataFrame(
    {
        "a": np.arange(6),
        "b": np.random.randn(6),
    },
    index=["a", "a", "b", "c", "b", "a"],
)
df3

   a         b
a  0  0.899682
a  1 -1.700421
b  2  1.125290
c  3  0.371708
b  4  1.266363
a  5  0.935600

In [172]:
df3.index.duplicated()

array([False,  True, False, False,  True,  True])

In [173]:
df3[~df3.index.duplicated()]

   a         b
a  0  0.899682
b  2  1.125290
c  3  0.371708

# Index objects

In [174]:
# Create an Index by passing a list of strings
index = pd.Index(["e", "d", "a", "b"])
index

Index(['e', 'd', 'a', 'b'], dtype='object')

In [175]:
"d" in index

True

In [176]:
# or numbers
index = pd.Index([1, 5, 12])
index

Index([1, 5, 12], dtype='int64')

In [177]:
5 in index

True

In [178]:
# Provide an explicit dtype when creating an Index
index = pd.Index(["e", "d", "a", "b"], dtype="string")
index

Index(['e', 'd', 'a', 'b'], dtype='string')

In [179]:
index = pd.Index([1, 5, 12], dtype="int8")
index

Index([1, 5, 12], dtype='int8')

In [180]:
index = pd.Index([1, 5, 12], dtype="float32")
index

Index([1.0, 5.0, 12.0], dtype='float32')

In [181]:
# An Index can have a name
index = pd.Index(["e", "d", "a", "b"], name="something")
index.name

'something'

In [182]:
index = pd.Index(list(range(5)), name="rows")
columns = pd.Index(["A", "B", "C"], name="cols")

df = pd.DataFrame(np.random.randn(5, 3), index=index, columns=columns)
df

cols         A         B         C
rows
0    -0.789862 -0.867798 -0.716453
1    -1.160760  0.723912 -0.686472
2    -0.921616 -0.311037  0.246404
3    -1.469215  0.743442  0.427010
4     0.401007 -0.842560 -1.131169

In [183]:
df.A

rows
0   -0.789862
1   -1.160760
2   -0.921616
3   -1.469215
4    0.401007
Name: A, dtype: float64

## Setting metadata

In [184]:
ind = pd.Index([1, 2, 3])
ind.rename("apple")

Index([1, 2, 3], dtype='int64', name='apple')

In [185]:
ind

Index([1, 2, 3], dtype='int64')

In [186]:
ind = ind.set_names(["apple"])
ind.name = "bob"
ind

Index([1, 2, 3], dtype='int64', name='bob')

# Set an Index

In [187]:
data = pd.DataFrame(
    {
        "a": ["bar", "bar", "foo", "foo"],
        "b": ["one", "two", "one", "two"],
        "c": ["z", "y", "x", "w"],
        "d": [1.0, 2.0, 3, 4],
    }
)
data

     a    b  c    d
0  bar  one  z  1.0
1  bar  two  y  2.0
2  foo  one  x  3.0
3  foo  two  w  4.0

In [188]:
# Use column "c" as the index, removing it from the df
indexed1 = data.set_index("c")
indexed1

     a    b    d
c
z  bar  one  1.0
y  bar  two  2.0
x  foo  one  3.0
w  foo  two  4.0

In [189]:
# Reset the Index
data

     a    b  c    d
0  bar  one  z  1.0
1  bar  two  y  2.0
2  foo  one  x  3.0
3  foo  two  w  4.0

In [190]:
data.reset_index()

   index    a    b  c    d
0      0  bar  one  z  1.0
1      1  bar  two  y  2.0
2      2  foo  one  x  3.0
3      3  foo  two  w  4.0

# Returning a View versus a Copy

In [191]:
dfmi = pd.DataFrame(
    [
        list("abcd"),
        list("efgh"),
        list("ijkl"),
        list("mnop"),
    ],
    columns=pd.MultiIndex.from_product(
        [
            ["one", "two"],
            ["first", "second"],
        ]
    ),
)
dfmi

    one          two
  first second first second
0     a      b     c      d
1     e      f     g      h
2     i      j     k      l
3     m      n     o      p

In [192]:
# First access method: chained []
dfmi["one"]["second"]

0    b
1    f
2    j
3    n
Name: second, dtype: object

In [193]:
# Second access method: labeled-based location (preferred method)
dfmi.loc[:, ("one", "second")]

0    b
1    f
2    j
3    n
Name: (one, second), dtype: object