In [2]:
import numpy as np
import pandas as pd

# Hierarchical Indexing (MultiIndex)

# Creating a MultiIndex (hierarchical index) Object

In [3]:
# Create a MultiIndex from tuples
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

tuples = list(zip(*arrays))
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [4]:
index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [5]:
s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one      -0.035746
       two       1.970231
baz    one      -1.300263
       two      -0.437026
foo    one       0.673253
       two      -0.130058
qux    one      -0.464251
       two      -1.063216
dtype: float64

In [6]:
# Create a MultiIndex from the cross product of two iterables
# i.e. include every pairing of the elements
iterables = [
    ["bar", "baz", "foo", "qux"],
    ["one", "two"],
]

pd.MultiIndex.from_product(iterables, names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [7]:
# Create a MultiIndex from a DataFrame
df = pd.DataFrame(
    [
        ["bar", "one"],
        ["bar", "two"],
        ["foo", "one"],
        ["foo", "two"],
    ],
    columns=["first", "second"],
)

pd.MultiIndex.from_frame(df)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

In [8]:
# Or pass a list of arrays directly to a Series (or DataFrame)
arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"]),
]

s = pd.Series(np.random.randn(8), index=arrays)
s

bar  one    0.873488
     two    0.912553
baz  one   -2.945189
     two   -0.287913
foo  one   -0.445447
     two   -1.059883
qux  one   -1.656149
     two    1.484690
dtype: float64

In [9]:
df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
df

                0         1         2         3
bar one  1.189487  0.812054  0.851119  0.151046
    two -0.575063 -0.411179 -0.495328  1.466947
baz one  1.481680  0.077147  0.255315 -1.552715
    two  0.364417 -2.038364  0.705180 -0.107285
foo one -0.306407  1.987208  0.683942 -0.449367
    two  1.116022  0.440243 -0.525494  0.863770
qux one  0.546586 -0.415123  0.373719 -0.557403
    two  1.012676  0.383054 -1.509811 -1.751337

In [10]:
# names holds the names of the levels
# if no names argument was provided, None is returned
df.index.names

FrozenList([None, None])

In [11]:
# The MultiIndex we created can be used on any axis of the DataFrame
# Above it was used as row labels (axis=0)
# Below as column labels
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A       0.616765  1.507959  0.628502  3.262452  0.103991 -1.181384 -0.006230
B      -0.158517  0.416035 -0.004476  1.646731  0.765525 -0.680617 -0.701543
C       0.577181  1.761319  1.871738  0.317237 -1.286284  0.159517 -0.019492

first
second       two
A      -0.801557
B       0.571681
C       0.833670

In [12]:
pd.DataFrame(np.random.randn(6, 6), index=index[:6], columns=index[:6])

first              bar                 baz                 foo
second             one       two       one       two       one       two
first second
bar   one     0.092784  0.482271  0.840859  1.634654  0.139539  0.138355
      two    -0.036902  0.071598 -0.094888  0.466944 -1.231106  0.461362
baz   one     1.976419 -0.709978 -2.022016 -0.882506 -1.080036 -1.458216
      two    -0.681293  0.205936  0.467970 -0.664751  0.275472 -1.114986
foo   one    -2.252978 -1.956864  0.555852  2.847183 -1.461988  0.437171
      two     0.496290 -0.757231  1.852113  0.208830  0.071900  1.187345

In [13]:
with pd.option_context("display.multi_sparse", False):
    print(df)

first        bar       bar       baz       baz       foo       foo       qux  \
second       one       two       one       two       one       two       one
A       0.616765  1.507959  0.628502  3.262452  0.103991 -1.181384 -0.006230
B      -0.158517  0.416035 -0.004476  1.646731  0.765525 -0.680617 -0.701543
C       0.577181  1.761319  1.871738  0.317237 -1.286284  0.159517 -0.019492

first        qux
second       two
A      -0.801557
B       0.571681
C       0.833670

In [14]:
# Can also use tuples as row labels
pd.Series(np.random.randn(8), index=tuples)

(bar, one)    1.514144
(bar, two)   -0.593488
(baz, one)   -0.176215
(baz, two)    1.013626
(foo, one)    0.364441
(foo, two)   -0.972501
(qux, one)    1.006623
(qux, two)    2.624890
dtype: float64

## Reconstructing the Level Labels

In [15]:
index.get_level_values(0)

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [16]:
index.get_level_values("second")

Index(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'], dtype='object', name='second')

## Basic Indexing on Axis with MultiIndex

In [17]:
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A       0.616765  1.507959  0.628502  3.262452  0.103991 -1.181384 -0.006230
B      -0.158517  0.416035 -0.004476  1.646731  0.765525 -0.680617 -0.701543
C       0.577181  1.761319  1.871738  0.317237 -1.286284  0.159517 -0.019492

first
second       two
A      -0.801557
B       0.571681
C       0.833670

In [18]:
df["bar"]

second       one       two
A       0.616765  1.507959
B      -0.158517  0.416035
C       0.577181  1.761319

In [19]:
df["bar", "one"]

A    0.616765
B   -0.158517
C    0.577181
Name: (bar, one), dtype: float64

In [20]:
df["bar"]["one"]

A    0.616765
B   -0.158517
C    0.577181
Name: one, dtype: float64

In [21]:
s["qux"]

one   -1.656149
two    1.484690
dtype: float64

## Defined Levels

In [22]:
df.columns.levels  # Original MultiIndex

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [23]:
df[["foo", "qux"]].columns.levels  # Sliced

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [24]:
# To only see the used levels
df[["foo", "qux"]].columns.get_level_values(0)

Index(['foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [25]:
# To reconstruct the MultiIndex with only the used levels
new_mi = df[["foo", "qux"]].columns.remove_unused_levels()
new_mi.levels

FrozenList([['foo', 'qux'], ['one', 'two']])

## Data Alignment and Using reindex

In [26]:
# When the objects have different indexes (MultiIndexes)
# we have data alignment.
s  # a Series with hierarchical index

bar  one    0.873488
     two    0.912553
baz  one   -2.945189
     two   -0.287913
foo  one   -0.445447
     two   -1.059883
qux  one   -1.656149
     two    1.484690
dtype: float64

In [27]:
# Add two Series element-wise. The second one has elements
# from the start up to (qux, one) - not included.
# So, for example (qux, one) i.e. 0.502 + Nan -> Nan
s + s[:-2]

bar  one    1.746975
     two    1.825105
baz  one   -5.890378
     two   -0.575825
foo  one   -0.890895
     two   -2.119767
qux  one         NaN
     two         NaN
dtype: float64

In [28]:
# step 2: include (bar, one), (baz, one), (foo, one) and (qux, one).
#       : so for example (bar, two): -1.905 + NaN -> NaN
s + s[::2]

bar  one    1.746975
     two         NaN
baz  one   -5.890378
     two         NaN
foo  one   -0.890895
     two         NaN
qux  one   -3.312298
     two         NaN
dtype: float64

In [29]:
# Conform the Series to a new index
s.reindex(index[:3])

first  second
bar    one       0.873488
       two       0.912553
baz    one      -2.945189
dtype: float64

In [30]:
# Use a list of tuples for re-indexing
s.reindex([("foo", "two"), ("bar", "one"), ("qux", "one"), ("baz", "one")])

foo  two   -1.059883
bar  one    0.873488
qux  one   -1.656149
baz  one   -2.945189
dtype: float64

# Advanced Indexing with Hierarchical Data

In [31]:
# Transpose the rows and columns of the DataFrame
df = df.T
df

                     A         B         C
first second
bar   one     0.616765 -0.158517  0.577181
      two     1.507959  0.416035  1.761319
baz   one     0.628502 -0.004476  1.871738
      two     3.262452  1.646731  0.317237
foo   one     0.103991  0.765525 -1.286284
      two    -1.181384 -0.680617  0.159517
qux   one    -0.006230 -0.701543 -0.019492
      two    -0.801557  0.571681  0.833670

In [32]:
# Refer to the MultiIndex keys as tuples
df.loc[("bar", "two")]

A    1.507959
B    0.416035
C    1.761319
Name: (bar, two), dtype: float64

In [33]:
# Same as above, but index a specific column
df.loc[("bar", "two"), "A"]

np.float64(1.5079591227318698)

In [34]:
# Get all elements with "bar" in the first level
df.loc[("bar",)]  # or just .loc["bar"]

               A         B         C
second
one     0.616765 -0.158517  0.577181
two     1.507959  0.416035  1.761319

In [35]:
# Partial slicing from "bar" to "foo"
df.loc["baz":"foo"]  # NOTE: here the stop "foo" is included!

                     A         B         C
first second
baz   one     0.628502 -0.004476  1.871738
      two     3.262452  1.646731  0.317237
foo   one     0.103991  0.765525 -1.286284
      two    -1.181384 -0.680617  0.159517

In [36]:
df.loc[("baz", "two"):("qux", "one")]

                     A         B         C
first second
baz   two     3.262452  1.646731  0.317237
foo   one     0.103991  0.765525 -1.286284
      two    -1.181384 -0.680617  0.159517
qux   one    -0.006230 -0.701543 -0.019492

In [37]:
df.loc[("baz", "two"):"foo"]

                     A         B         C
first second
baz   two     3.262452  1.646731  0.317237
foo   one     0.103991  0.765525 -1.286284
      two    -1.181384 -0.680617  0.159517

In [38]:
# Reindex by passing a list of tuples/labels
# NOTE: we pass a LIST of tuples, not just tuples as previously!
df.loc[[("bar", "two"), ("qux", "one")]]

                     A         B         C
first second
bar   two     1.507959  0.416035  1.761319
qux   one    -0.006230 -0.701543 -0.019492

In [39]:
s = pd.Series(
    [1, 2, 3, 4, 5, 6],
    index=pd.MultiIndex.from_product([["A", "B"], ["c", "d", "e"]]),
)
s

A  c    1
   d    2
   e    3
B  c    4
   d    5
   e    6
dtype: int64

In [40]:
# List of tuples
# In a hierarchical index, each tuple represents a complete key.
s.loc[[("A", "c"), ("B", "d")]]

A  c    1
B  d    5
dtype: int64

In [41]:
# Tuple of lists
# A list specifies several keys.
s.loc[(["A", "B"], ["c", "d"])]

A  c    1
   d    2
B  c    4
   d    5
dtype: int64

## Using Slicers

In [42]:
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]


miindex = pd.MultiIndex.from_product(
    [mklbl("A", 4), mklbl("B", 2), mklbl("C", 4), mklbl("D", 2)],
)
micolumns = pd.MultiIndex.from_tuples(
    [("a", "foo"), ("a", "bar"), ("b", "foo"), ("b", "bah")],
    names=["lvl0", "lvl1"],
)

dfmi = (
    pd.DataFrame(
        np.arange(len(miindex) * len(micolumns)).reshape(len(miindex), len(micolumns)),
        index=miindex,
        columns=micolumns,
    )
    .sort_index()
    .sort_index(axis=1)
)

dfmi

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0    9    8   11   10
         D1   13   12   15   14
      C2 D0   17   16   19   18
...          ...  ...  ...  ...
A3 B1 C1 D1  237  236  239  238
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  249  248  251  250
         D1  253  252  255  254

[64 rows x 4 columns]

In [43]:
# Basic MultiIndex slicing using slices, lists & labels
dfmi.loc[(slice("A1", "A3"), slice(None), ["C1", "C3"]), :]

lvl0           a         b
lvl1         bar  foo  bah  foo
A1 B0 C1 D0   73   72   75   74
         D1   77   76   79   78
      C3 D0   89   88   91   90
         D1   93   92   95   94
   B1 C1 D0  105  104  107  106
         D1  109  108  111  110
      C3 D0  121  120  123  122
         D1  125  124  127  126
A2 B0 C1 D0  137  136  139  138
         D1  141  140  143  142
      C3 D0  153  152  155  154
         D1  157  156  159  158
   B1 C1 D0  169  168  171  170
         D1  173  172  175  174
      C3 D0  185  184  187  186
         D1  189  188  191  190
A3 B0 C1 D0  201  200  203  202
         D1  205  204  207  206
      C3 D0  217  216  219  218
         D1  221  220  223  222
   B1 C1 D0  233  232  235  234
         D1  237  236  239  238
      C3 D0  249  248  251  250
         D1  253  252  255  254

In [44]:
idx = pd.IndexSlice
dfmi.loc[idx[:, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A0 B0 C1 D0    8   10
         D1   12   14
      C3 D0   24   26
         D1   28   30
   B1 C1 D0   40   42
         D1   44   46
      C3 D0   56   58
         D1   60   62
A1 B0 C1 D0   72   74
         D1   76   78
      C3 D0   88   90
         D1   92   94
   B1 C1 D0  104  106
         D1  108  110
      C3 D0  120  122
         D1  124  126
A2 B0 C1 D0  136  138
         D1  140  142
      C3 D0  152  154
         D1  156  158
   B1 C1 D0  168  170
         D1  172  174
      C3 D0  184  186
         D1  188  190
A3 B0 C1 D0  200  202
         D1  204  206
      C3 D0  216  218
         D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

In [45]:
dfmi.loc["A1", (slice(None), "foo")]

lvl0        a    b
lvl1      foo  foo
B0 C0 D0   64   66
      D1   68   70
   C1 D0   72   74
      D1   76   78
   C2 D0   80   82
      D1   84   86
   C3 D0   88   90
      D1   92   94
B1 C0 D0   96   98
      D1  100  102
   C1 D0  104  106
      D1  108  110
   C2 D0  112  114
      D1  116  118
   C3 D0  120  122
      D1  124  126

In [46]:
dfmi.loc[idx[:, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A0 B0 C1 D0    8   10
         D1   12   14
      C3 D0   24   26
         D1   28   30
   B1 C1 D0   40   42
         D1   44   46
      C3 D0   56   58
         D1   60   62
A1 B0 C1 D0   72   74
         D1   76   78
      C3 D0   88   90
         D1   92   94
   B1 C1 D0  104  106
         D1  108  110
      C3 D0  120  122
         D1  124  126
A2 B0 C1 D0  136  138
         D1  140  142
      C3 D0  152  154
         D1  156  158
   B1 C1 D0  168  170
         D1  172  174
      C3 D0  184  186
         D1  188  190
A3 B0 C1 D0  200  202
         D1  204  206
      C3 D0  216  218
         D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

In [47]:
# Boolean indexer
mask = dfmi[("a", "foo")] > 200
dfmi.loc[idx[mask, :, ["C1", "C3"]], idx[:, "foo"]]

lvl0           a    b
lvl1         foo  foo
A3 B0 C1 D1  204  206
      C3 D0  216  218
         D1  220  222
   B1 C1 D0  232  234
         D1  236  238
      C3 D0  248  250
         D1  252  254

In [48]:
# Using the "axis" argument
dfmi.loc(axis=0)[:, :, ["C1", "C3"]]

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C1 D0    9    8   11   10
         D1   13   12   15   14
      C3 D0   25   24   27   26
         D1   29   28   31   30
   B1 C1 D0   41   40   43   42
         D1   45   44   47   46
      C3 D0   57   56   59   58
         D1   61   60   63   62
A1 B0 C1 D0   73   72   75   74
         D1   77   76   79   78
      C3 D0   89   88   91   90
         D1   93   92   95   94
   B1 C1 D0  105  104  107  106
         D1  109  108  111  110
      C3 D0  121  120  123  122
         D1  125  124  127  126
A2 B0 C1 D0  137  136  139  138
         D1  141  140  143  142
      C3 D0  153  152  155  154
         D1  157  156  159  158
   B1 C1 D0  169  168  171  170
         D1  173  172  175  174
      C3 D0  185  184  187  186
         D1  189  188  191  190
A3 B0 C1 D0  201  200  203  202
         D1  205  204  207  206
      C3 D0  217  216  219  218
         D1  221  220  223  222
   B1 C1 D0  233  232  235  234
         D1  237  236  239  238
      C3 D0  249  248  251  250
         D1  253  252  255  254

In [49]:
# Set the values
df2 = dfmi.copy()
df2.loc(axis=0)[:, :, ["C1", "C3"]] = -10
df2

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0  -10  -10  -10  -10
         D1  -10  -10  -10  -10
      C2 D0   17   16   19   18
...          ...  ...  ...  ...
A3 B1 C1 D1  -10  -10  -10  -10
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  -10  -10  -10  -10
         D1  -10  -10  -10  -10

[64 rows x 4 columns]

In [50]:
df2 = dfmi.copy()
df2.loc[idx[:, :, ["C1", "C3"]], :] = df2 * 1000
df2

lvl0              a               b
lvl1            bar     foo     bah     foo
A0 B0 C0 D0       1       0       3       2
         D1       5       4       7       6
      C1 D0    9000    8000   11000   10000
         D1   13000   12000   15000   14000
      C2 D0      17      16      19      18
...             ...     ...     ...     ...
A3 B1 C1 D1  237000  236000  239000  238000
      C2 D0     241     240     243     242
         D1     245     244     247     246
      C3 D0  249000  248000  251000  250000
         D1  253000  252000  255000  254000

[64 rows x 4 columns]

## Cross-Section

In [51]:
df

                     A         B         C
first second
bar   one     0.616765 -0.158517  0.577181
      two     1.507959  0.416035  1.761319
baz   one     0.628502 -0.004476  1.871738
      two     3.262452  1.646731  0.317237
foo   one     0.103991  0.765525 -1.286284
      two    -1.181384 -0.680617  0.159517
qux   one    -0.006230 -0.701543 -0.019492
      two    -0.801557  0.571681  0.833670

In [52]:
# Use xs to select a particular level
df.xs("one", level="second")

              A         B         C
first
bar    0.616765 -0.158517  0.577181
baz    0.628502 -0.004476  1.871738
foo    0.103991  0.765525 -1.286284
qux   -0.006230 -0.701543 -0.019492

In [53]:
# Using the slicers
df.loc[(slice(None), "one"), :]

                     A         B         C
first second
bar   one     0.616765 -0.158517  0.577181
baz   one     0.628502 -0.004476  1.871738
foo   one     0.103991  0.765525 -1.286284
qux   one    -0.006230 -0.701543 -0.019492

In [54]:
df = df.T
df.xs("one", level="second", axis=1)

first       bar       baz       foo       qux
A      0.616765  0.628502  0.103991 -0.006230
B     -0.158517 -0.004476  0.765525 -0.701543
C      0.577181  1.871738 -1.286284 -0.019492

In [55]:
# Selection with mutiple keys
df.xs(("one", "bar"), level=("second", "first"), axis=1)

first        bar
second       one
A       0.616765
B      -0.158517
C       0.577181

## Advanced Reindexing and Alignment

In [56]:
# Broadcast values across a level.
midx = pd.MultiIndex(
    levels=[["zero", "one"], ["x", "y"]],
    codes=[[1, 1, 0, 0], [1, 0, 1, 0]],
)

df = pd.DataFrame(np.random.randn(4, 2), index=midx)
df

               0         1
one  y -0.398318  0.289966
     x -0.689626 -0.232176
zero y  0.180581  1.256358
     x  0.718708 -0.400164

In [57]:
df2 = df.groupby(level=0).mean()
df2

             0         1
one  -0.543972  0.028895
zero  0.449645  0.428097

In [58]:
df2.reindex(df.index, level=0)

               0         1
one  y -0.543972  0.028895
     x -0.543972  0.028895
zero y  0.449645  0.428097
     x  0.449645  0.428097

In [59]:
# aligning
df_aligned, df2_aligned = df.align(df2, level=0)
df_aligned

               0         1
one  y -0.398318  0.289966
     x -0.689626 -0.232176
zero y  0.180581  1.256358
     x  0.718708 -0.400164

In [60]:
df2_aligned

               0         1
one  y -0.543972  0.028895
     x -0.543972  0.028895
zero y  0.449645  0.428097
     x  0.449645  0.428097

## Swapping Levels with swaplevel

In [61]:
df[:5]

               0         1
one  y -0.398318  0.289966
     x -0.689626 -0.232176
zero y  0.180581  1.256358
     x  0.718708 -0.400164

In [62]:
df[:5].swaplevel(0, 1, axis=0)

               0         1
y one  -0.398318  0.289966
x one  -0.689626 -0.232176
y zero  0.180581  1.256358
x zero  0.718708 -0.400164

## Reordering Levels

In [63]:
df[:5].reorder_levels([1, 0], axis=0)

               0         1
y one  -0.398318  0.289966
x one  -0.689626 -0.232176
y zero  0.180581  1.256358
x zero  0.718708 -0.400164

## Renaming names of an Index or MultiIndex

In [64]:
df.rename(columns={0: "col0", 1: "col1"})

            col0      col1
one  y -0.398318  0.289966
     x -0.689626 -0.232176
zero y  0.180581  1.256358
     x  0.718708 -0.400164

In [65]:
df.rename(index={"one": "two", "y": "z"})

               0         1
two  z -0.398318  0.289966
     x -0.689626 -0.232176
zero z  0.180581  1.256358
     x  0.718708 -0.400164

In [66]:
df.rename_axis(index=["abc", "def"])

                 0         1
abc  def
one  y   -0.398318  0.289966
     x   -0.689626 -0.232176
zero y    0.180581  1.256358
     x    0.718708 -0.400164

In [67]:
df.rename_axis(columns="Cols").columns

RangeIndex(start=0, stop=2, step=1, name='Cols')

# Sorting a MultiIndex

In [68]:
import random

random.shuffle(tuples)

s = pd.Series(np.random.randn(8), index=pd.MultiIndex.from_tuples(tuples))

s

qux  one   -0.521489
foo  one   -0.331422
qux  two    0.067522
foo  two   -0.741148
bar  one   -0.318027
     two   -0.576516
baz  one    0.262260
     two   -0.447564
dtype: float64

In [69]:
# Sort the Series by index labels
s.sort_index()

bar  one   -0.318027
     two   -0.576516
baz  one    0.262260
     two   -0.447564
foo  one   -0.331422
     two   -0.741148
qux  one   -0.521489
     two    0.067522
dtype: float64

In [70]:
s.sort_index(level=0)

bar  one   -0.318027
     two   -0.576516
baz  one    0.262260
     two   -0.447564
foo  one   -0.331422
     two   -0.741148
qux  one   -0.521489
     two    0.067522
dtype: float64

In [71]:
s.sort_index(level=1)

bar  one   -0.318027
baz  one    0.262260
foo  one   -0.331422
qux  one   -0.521489
bar  two   -0.576516
baz  two   -0.447564
foo  two   -0.741148
qux  two    0.067522
dtype: float64

In [72]:
# If the levels of the MultiIndex have names, we can pass the level name to sort_index
s.index = s.index.set_names(["L1", "L2"])
s.sort_index(level="L1")

L1   L2
bar  one   -0.318027
     two   -0.576516
baz  one    0.262260
     two   -0.447564
foo  one   -0.331422
     two   -0.741148
qux  one   -0.521489
     two    0.067522
dtype: float64

In [73]:
s.sort_index(level="L2")

L1   L2
bar  one   -0.318027
baz  one    0.262260
foo  one   -0.331422
qux  one   -0.521489
bar  two   -0.576516
baz  two   -0.447564
foo  two   -0.741148
qux  two    0.067522
dtype: float64

In [74]:
df.T.sort_index(level=1, axis=1)

        one      zero       one      zero
          x         x         y         y
0 -0.689626  0.718708 -0.398318  0.180581
1 -0.232176 -0.400164  0.289966  1.256358

In [75]:
# Indexing works with data that are not sorted
dfm = pd.DataFrame(
    {
        "jim": [0, 0, 1, 1],
        "joe": ["x", "x", "z", "y"],
        "jolie": np.random.randn(4),
    }
)

dfm.set_index(["jim", "joe"], inplace=True)

dfm

            jolie
jim joe
0   x   -0.007190
    x   -1.269518
1   z    0.400579
    y   -0.095460

In [76]:
dfm.loc[1, "z"]

C:\Users\nkmil\AppData\Local\Temp\ipykernel_18088\3228926249.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  dfm.loc[1, "z"]

            jolie
jim joe
1   z    0.400579

In [77]:
# Check if the index is sorted
dfm.index.is_monotonic_increasing

False

In [78]:
dfm.sort_index(inplace=True)
dfm

            jolie
jim joe
0   x   -0.007190
    x   -1.269518
1   y   -0.095460
    z    0.400579

In [79]:
dfm.index.is_monotonic_increasing

True

In [80]:
dfm.loc[(0, "y"):(1, "z")]

            jolie
jim joe
1   y   -0.095460
    z    0.400579

# Take Methods

In [81]:
# take() retrieves elements along a given axis, at the given indices.
index = pd.Index(np.random.randint(0, 1000, 10))
index

Index([140, 805, 128, 239, 81, 320, 745, 482, 139, 886], dtype='int32')

In [82]:
positions = [0, 9, 3]
index[positions]

Index([140, 886, 239], dtype='int32')

In [83]:
index.take(positions)

Index([140, 886, 239], dtype='int32')

In [84]:
ser = pd.Series(np.random.randn(10))
ser.iloc[positions]

0   -0.547211
9    0.351642
3   -0.568672
dtype: float64

In [85]:
ser.take(positions)

0   -0.547211
9    0.351642
3   -0.568672
dtype: float64

In [86]:
frm = pd.DataFrame(np.random.randn(5, 3))
frm.take([1, 4, 3])

          0         1         2
1  0.140258 -0.740684  0.671192
4 -0.843638  0.110978 -0.035097
3  1.491311 -1.804780 -0.288733

In [87]:
frm.take([0, 2], axis=1)

          0         2
0  0.733550  0.066417
1  0.140258  0.671192
2 -1.286455  2.091714
3  1.491311 -0.288733
4 -0.843638 -0.035097

# Index Types

Apart from MultiIndex there are also:
- DatetimeIndex
- PeriodIndex
- TimedeltaIndex
- CategoricalIndex
- RangeIndex
- IntervalIndex

## CategoricalIndex

Allows efficient indexing of an index with a large number of <b><u>duplicated</u></b> elements.

In [88]:
from pandas.api.types import CategoricalDtype

df = pd.DataFrame({"A": np.arange(6), "B": list("aabbca")})

df["B"] = df["B"].astype(CategoricalDtype(list("cab")))

df

   A  B
0  0  a
1  1  a
2  2  b
3  3  b
4  4  c
5  5  a

In [89]:
df.dtypes

A       int64
B    category
dtype: object

In [90]:
df["B"].cat.categories

Index(['c', 'a', 'b'], dtype='object')

In [91]:
# Set as index the existing column "B"
df2 = df.set_index("B")

df2.index

CategoricalIndex(['a', 'a', 'b', 'b', 'c', 'a'], categories=['c', 'a', 'b'], ordered=False, dtype='category', name='B')

In [92]:
df2.loc["a"]

   A
B
a  0
a  1
a  5

In [93]:
df2.loc["a"].index

CategoricalIndex(['a', 'a', 'a'], categories=['c', 'a', 'b'], ordered=False, dtype='category', name='B')

In [94]:
# Sort the index by the order of the categories as we specified it!
df2.sort_index()

   A
B
c  4
a  0
a  1
a  5
b  2
b  3

In [95]:
df2.groupby(level=0, observed=True).sum()

   A
B
c  4
a  6
b  5

In [96]:
df2.groupby(level=0, observed=True).sum().index

CategoricalIndex(['c', 'a', 'b'], categories=['c', 'a', 'b'], ordered=False, dtype='category', name='B')

In [97]:
df3 = pd.DataFrame({"A": np.arange(3), "B": pd.Series(list("abc")).astype("category")})

df3 = df3.set_index("B")

df3

   A
B
a  0
b  1
c  2

In [98]:
df3.reindex(["a", "e"])

     A
B
a  0.0
e  NaN

In [99]:
df3.reindex(["a", "e"]).index

Index(['a', 'e'], dtype='object', name='B')

In [100]:
df3.reindex(pd.Categorical(["a", "e"], categories=list("abe")))

     A
B
a  0.0
e  NaN

In [101]:
df3.reindex(pd.Categorical(["a", "e"], categories=list("abe"))).index

CategoricalIndex(['a', 'e'], categories=['a', 'b', 'e'], ordered=False, dtype='category', name='B')

## RangeIndex
This is the default index for all <b style="color:red;">DataFrame</b> and <b style="color:red;">Series</b> objects.

In [103]:
idx = pd.RangeIndex(5)
idx

RangeIndex(start=0, stop=5, step=1)

In [104]:
ser = pd.Series([1, 2, 3])
ser.index

RangeIndex(start=0, stop=3, step=1)

In [105]:
df = pd.DataFrame([[1, 2], [3, 4]])
df.index

RangeIndex(start=0, stop=2, step=1)

In [106]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [107]:
idx[[0, 2]]

Index([0, 2], dtype='int64')

## IntervalIndex

In [110]:
df = pd.DataFrame(
    {"A": [1, 2, 3, 4]},
    index=pd.IntervalIndex.from_breaks([0, 1, 2, 3, 4]),
)
df

        A
(0, 1]  1
(1, 2]  2
(2, 3]  3
(3, 4]  4

In [ ]:
# Label-based indexing via .loc - using labels
df.loc[2]

A    2
Name: (1, 2], dtype: int64

In [112]:
df.loc[[2, 3]]

        A
(1, 2]  2
(2, 3]  3

In [113]:
df.loc[2.5]

A    3
Name: (2, 3], dtype: int64

In [114]:
df.loc[[2.5, 3.5]]

        A
(2, 3]  3
(3, 4]  4

In [115]:
# Using intervals - returns exact matches
df.loc[pd.Interval(1, 2)]

A    2
Name: (1, 2], dtype: int64

In [116]:
# Selecting all intervals that overlap a given Interval
idxr = df.index.overlaps(pd.Interval(0.5, 2.5))
idxr

array([ True,  True,  True, False])

In [117]:
df[idxr]

        A
(0, 1]  1
(1, 2]  2
(2, 3]  3

### Binning data with cut and qcut

In [ ]:
# cut() bins values into discrete intervals
c = pd.cut(range(4), bins=2)
c

[(-0.003, 1.5], (-0.003, 1.5], (1.5, 3.0], (1.5, 3.0]]
Categories (2, interval[float64, right]): [(-0.003, 1.5] < (1.5, 3.0]]

In [119]:
c.categories

IntervalIndex([(-0.003, 1.5], (1.5, 3.0]], dtype='interval[float64, right]')

In [120]:
pd.cut([0, 3, 5, 1], bins=c.categories)

[(-0.003, 1.5], (1.5, 3.0], NaN, (-0.003, 1.5]]
Categories (2, interval[float64, right]): [(-0.003, 1.5] < (1.5, 3.0]]

### Generating ranges of intervals

In [121]:
pd.interval_range(start=0, end=5)

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]], dtype='interval[int64, right]')

In [122]:
pd.interval_range(start=pd.Timestamp("2017-01-01"), periods=4)

IntervalIndex([(2017-01-01 00:00:00, 2017-01-02 00:00:00],
               (2017-01-02 00:00:00, 2017-01-03 00:00:00],
               (2017-01-03 00:00:00, 2017-01-04 00:00:00],
               (2017-01-04 00:00:00, 2017-01-05 00:00:00]],
              dtype='interval[datetime64[ns], right]')

In [123]:
pd.interval_range(end=pd.Timedelta("3 days"), periods=3)

IntervalIndex([(0 days 00:00:00, 1 days 00:00:00],
               (1 days 00:00:00, 2 days 00:00:00],
               (2 days 00:00:00, 3 days 00:00:00]],
              dtype='interval[timedelta64[ns], right]')

In [124]:
pd.interval_range(start=0, periods=5, freq=1.5)

IntervalIndex([(0.0, 1.5], (1.5, 3.0], (3.0, 4.5], (4.5, 6.0], (6.0, 7.5]], dtype='interval[float64, right]')

In [125]:
pd.interval_range(start=0, end=4, closed="both")

IntervalIndex([[0, 1], [1, 2], [2, 3], [3, 4]], dtype='interval[int64, both]')

In [126]:
pd.interval_range(start=0, end=4, closed="neither")

IntervalIndex([(0, 1), (1, 2), (2, 3), (3, 4)], dtype='interval[int64, neither]')

In [127]:
pd.interval_range(start=0, end=6, periods=4)

IntervalIndex([(0.0, 1.5], (1.5, 3.0], (3.0, 4.5], (4.5, 6.0]], dtype='interval[float64, right]')

In [129]:
# Non-monotonic indexes require exact matches
df = pd.DataFrame(
    index=[2, 3, 3, 4, 5],
    columns=["data"],
    data=list(range(5)),
)
df

   data
2     0
3     1
3     2
4     3
5     4

In [130]:
df.index.is_monotonic_increasing

True

In [131]:
# No rows 0 or 1, but still returns rows 2,3 (both of them), and 4:
df.loc[0:4, :]

   data
2     0
3     1
3     2
4     3

In [132]:
# Slice is are outside the index, so empty DataFrame is returned
df.loc[13:15, :]

Empty DataFrame
Columns: [data]
Index: []

In [133]:
df = pd.DataFrame(
    index=[2, 3, 1, 4, 3, 5],
    columns=["data"],
    data=list(range(6)),
)
df

   data
2     0
3     1
1     2
4     3
3     4
5     5

In [134]:
df.index.is_monotonic_increasing

False

In [135]:
# OK because 2 and 4 are in the index
df.loc[2:4, :]

   data
2     0
3     1
1     2
4     3

In [136]:
# Endpoints are inclusive
s = pd.Series(np.random.randn(6), index=list("abcdef"))
s

a   -0.658754
b    2.173371
c    0.142235
d    2.271538
e    0.266445
f   -0.963093
dtype: float64

In [137]:
s[2:5]

c    0.142235
d    2.271538
e    0.266445
dtype: float64