# Object Creation
## Series Creation
- Specifying dtype="category"
- Converting existing Series/DataFrame column, to a `category` dtype
- Using special functions such as `cut()`, which groups data into discrete bins
- By passing a Categorical object to a Series

In [1]:
import pandas as pd
import numpy as np

s = pd.Series(["a", "b", "c", "a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [2]:
df = pd.DataFrame({"A": ["a", "b", "c", "a"]})
df["B"] = df["A"].astype("category")
df

   A  B
0  a  a
1  b  b
2  c  c
3  a  a

In [3]:
df = pd.DataFrame({"value": np.random.randint(0, 100, 20)})
labels = ["{0} - {1}".format(i, i + 9) for i in range(0, 100, 10)]
labels

['0 - 9',
 '10 - 19',
 '20 - 29',
 '30 - 39',
 '40 - 49',
 '50 - 59',
 '60 - 69',
 '70 - 79',
 '80 - 89',
 '90 - 99']

In [4]:
df["group"] = pd.cut(df.value, range(0, 105, 10), right=False, labels=labels)
df.head(10)

   value    group
0     65  60 - 69
1     84  80 - 89
2     92  90 - 99
3     42  40 - 49
4     74  70 - 79
5     36  30 - 39
6     92  90 - 99
7     53  50 - 59
8     75  70 - 79
9     49  40 - 49

In [5]:
raw_cat = pd.Categorical(
    ["a", "b", "c", "a"],
    categories=["b", "c", "d"],
    ordered=False,
)

s = pd.Series(raw_cat)
s

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): ['b', 'c', 'd']

In [6]:
df = pd.DataFrame({"A": ["a", "b", "c", "a"]})
df["B"] = raw_cat
df

   A    B
0  a  NaN
1  b    b
2  c    c
3  a  NaN

In [7]:
df.dtypes

A      object
B    category
dtype: object

## DataFrame Creation

In [8]:
df = pd.DataFrame({"A": list("abca"), "B": list("bccd")}, dtype="category")
df.dtypes

A    category
B    category
dtype: object

In [9]:
df["A"]

0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (3, object): ['a', 'b', 'c']

In [10]:
df["B"]

0    b
1    c
2    c
3    d
Name: B, dtype: category
Categories (3, object): ['b', 'c', 'd']

In [11]:
df = pd.DataFrame({"A": list("abca"), "B": list("bccd")})
df_cat = df.astype("category")
df_cat.dtypes

A    category
B    category
dtype: object

In [12]:
df_cat["A"]

0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (3, object): ['a', 'b', 'c']

In [13]:
df_cat["B"]

0    b
1    c
2    c
3    d
Name: B, dtype: category
Categories (3, object): ['b', 'c', 'd']

## Controlling Behavior

In [14]:
# To control ordering and specifying the categories:
from pandas.api.types import CategoricalDtype

s = pd.Series(["a", "b", "c", "a"])
cat_type = CategoricalDtype(categories=["b", "c", "d"], ordered=True)
s_cat = s.astype(cat_type)
s_cat

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): ['b' < 'c' < 'd']

In [15]:
df = pd.DataFrame({"A": list("abca"), "B": list("bccd")})
cat_type = CategoricalDtype(categories=list("abcd"), ordered=True)
df_cat = df.astype(cat_type)

df_cat["A"]

0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (4, object): ['a' < 'b' < 'c' < 'd']

In [16]:
df_cat["B"]

0    b
1    c
2    c
3    d
Name: B, dtype: category
Categories (4, object): ['a' < 'b' < 'c' < 'd']

In [17]:
splitter = np.random.choice([0, 1], 5, p=[0.5, 0.5])
s = pd.Series(pd.Categorical.from_codes(splitter, categories=["train", "test"]))
s

0    train
1    train
2     test
3    train
4     test
dtype: category
Categories (2, object): ['train', 'test']

## Regaining Original Data

In [18]:
# The values are of type "object"
s = pd.Series(["a", "b", "c", "a"])
s

0    a
1    b
2    c
3    a
dtype: object

In [19]:
# Convert the entries into category dtype
s2 = s.astype("category")
s2

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [20]:
# Convert back to strings
s2.astype("str")

0    a
1    b
2    c
3    a
dtype: object

In [21]:
# Or use asarray()
np.asarray(s2)

array(['a', 'b', 'c', 'a'], dtype=object)

# CategoricalDtype

In [22]:
from pandas.api.types import CategoricalDtype

# The categories are inferred from the data, and assumed to be unordered
CategoricalDtype(["a", "b", "c"])

CategoricalDtype(categories=['a', 'b', 'c'], ordered=False, categories_dtype=object)

In [23]:
# Categories again are inferred, but now they are ordered
CategoricalDtype(["a", "b", "c"], ordered=True)

CategoricalDtype(categories=['a', 'b', 'c'], ordered=True, categories_dtype=object)

In [24]:
CategoricalDtype()

CategoricalDtype(categories=None, ordered=False, categories_dtype=None)

## Equality Semantics

In [25]:
# Two unordered categoricals with the same categories, are equal regardless of the order
c1 = CategoricalDtype(["a", "b", "c"], ordered=False)
c2 = CategoricalDtype(["b", "c", "a"], ordered=False)
c1 == c2

True

In [26]:
# One unordered and one ordered categorical with the same categories, are compared unequal
c1 = CategoricalDtype(["a", "b", "c"], ordered=False)
c2 = CategoricalDtype(["a", "b", "c"], ordered=True)
c1 == c2

False

In [27]:
# Also note:
c1 == "category"

True

# Description

In [28]:
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
df = pd.DataFrame({"cat": cat, "s": ["a", "c", "c", np.nan]})
df

   cat    s
0    a    a
1    c    c
2    c    c
3  NaN  NaN

In [29]:
df.describe()

       cat  s
count    3  3
unique   2  2
top      c  c
freq     2  2

# Working with Categories

In [30]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")

# Use the "cat" accessor to return the Series' categories...
s.cat.categories

Index(['a', 'b', 'c'], dtype='object')

In [31]:
# ... and whether they are ordered or not
s.cat.ordered

False

In [32]:
s = pd.Series(list("babc")).astype(CategoricalDtype(list("abcd")))
s

0    b
1    a
2    b
3    c
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [33]:
# return the categories:
s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
# return unique values in the Series
s.unique()

['b', 'a', 'c']
Categories (4, object): ['a', 'b', 'c', 'd']

## Renaming Categories

In [35]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [36]:
new_categories = [f"Group {g}" for g in s.cat.categories]
s = s.cat.rename_categories(new_categories)
s

0    Group a
1    Group b
2    Group c
3    Group a
dtype: category
Categories (3, object): ['Group a', 'Group b', 'Group c']

In [37]:
s = s.cat.rename_categories({1: "x", 2: "y", 3: "z"})
s

0    Group a
1    Group b
2    Group c
3    Group a
dtype: category
Categories (3, object): ['Group a', 'Group b', 'Group c']

## Appending New Categories

In [38]:
s = s.cat.add_categories([4])
s.cat.categories

Index(['Group a', 'Group b', 'Group c', 4], dtype='object')

## Removing Categories

In [39]:
s = s.cat.remove_categories([4])
s

0    Group a
1    Group b
2    Group c
3    Group a
dtype: category
Categories (3, object): ['Group a', 'Group b', 'Group c']

## Removing Unused Categories

In [40]:
s = pd.Series(pd.Categorical(["a", "b", "a"], categories=["a", "b", "c", "d"]))
s

0    a
1    b
2    a
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [41]:
s.cat.remove_unused_categories()

0    a
1    b
2    a
dtype: category
Categories (2, object): ['a', 'b']

## Setting Categories

In [42]:
s = pd.Series(["one", "two", "four", "-"], dtype="category")
s

0     one
1     two
2    four
3       -
dtype: category
Categories (4, object): ['-', 'four', 'one', 'two']

In [43]:
s = s.cat.set_categories(["one", "two", "three", "four"])
s

0     one
1     two
2    four
3     NaN
dtype: category
Categories (4, object): ['one', 'two', 'three', 'four']

# Sorting and Order

In [44]:
s = pd.Series(pd.Categorical(["a", "b", "c", "a"], ordered=False))
s = s.sort_values()
s = pd.Series(["a", "b", "c", "a"]).astype(CategoricalDtype(ordered=True))
s = s.sort_values()

s

0    a
3    a
1    b
2    c
dtype: category
Categories (3, object): ['a' < 'b' < 'c']

In [45]:
s.min(), s.max()

('a', 'c')

In [46]:
s.cat.as_ordered()

0    a
3    a
1    b
2    c
dtype: category
Categories (3, object): ['a' < 'b' < 'c']

In [47]:
s.cat.as_unordered()

0    a
3    a
1    b
2    c
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [48]:
# Sorting will use the ordered defined; not any lexical order!
s = pd.Series([1, 2, 3, 1], dtype="category")
s = s.cat.set_categories([2, 3, 1], ordered=True)
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

In [49]:
s = s.sort_values()
s

1    2
2    3
0    1
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

In [50]:
s.min(), s.max()

(np.int64(2), np.int64(1))

## Reordering

In [51]:
s = pd.Series([1, 2, 3, 1], dtype="category")
s = s.cat.reorder_categories([2, 3, 1], ordered=True)
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

In [52]:
s.sort_values()

1    2
2    3
0    1
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

# Multicolumn Sorting

In [53]:
dfs = pd.DataFrame(
    {
        "A": pd.Categorical(list("bbeebbaa"), categories=["e", "a", "b"], ordered=True),
        "B": [1, 2, 1, 2, 2, 1, 2, 1],
    }
)

In [54]:
dfs

   A  B
0  b  1
1  b  2
2  e  1
3  e  2
4  b  2
5  b  1
6  a  2
7  a  1

In [55]:
# NOTE: the sorting of categorical column "A", is determined by the "categories"
#       the sorting of numerical column "B", is numeric sorting
dfs.sort_values(by=["A", "B"])

   A  B
2  e  1
3  e  2
7  a  1
6  a  2
0  b  1
5  b  1
1  b  2
4  b  2

# Comparisons

In [56]:
cat = pd.Series([1, 2, 3]).astype(CategoricalDtype([3, 2, 1], ordered=True))
cat_base = pd.Series([2, 2, 2]).astype(CategoricalDtype([3, 2, 1], ordered=True))
cat_base2 = pd.Series([2, 2, 2]).astype(CategoricalDtype(ordered=True))

In [57]:
cat

0    1
1    2
2    3
dtype: category
Categories (3, int64): [3 < 2 < 1]

In [58]:
cat_base

0    2
1    2
2    2
dtype: category
Categories (3, int64): [3 < 2 < 1]

In [59]:
cat_base2

0    2
1    2
2    2
dtype: category
Categories (1, int64): [2]

In [60]:
# Compare two categoricals with the same: categories AND ordering
cat > cat_base

0     True
1    False
2    False
dtype: bool

In [61]:
cat > 2

0     True
1    False
2    False
dtype: bool

In [62]:
cat == cat_base

0    False
1     True
2    False
dtype: bool

# Operations

In [63]:
# Note that value_counts() uses all categories, even id they're not present in the Series
s = pd.Series(pd.Categorical(["a", "b", "c", "c"], categories=["c", "a", "b", "d"]))
s.value_counts()

c    2
a    1
b    1
d    0
Name: count, dtype: int64

In [64]:
columns = pd.Categorical(["One", "One", "Two"], categories=["One", "Two", "Three"], ordered=True)
df = df = pd.DataFrame(
    data=[[1, 2, 3], [4, 5, 6]],
    columns=pd.MultiIndex.from_arrays([["A", "B", "B"], columns]),
).T

In [65]:
df

       0  1
A One  1  4
B One  2  5
  Two  3  6

In [66]:
df.groupby(level=1, observed=False).sum()

       0  1
One    3  9
Two    3  6
Three  0  0

# Data Munging
## Getting

In [67]:
idx = pd.Index(["h", "i", "j", "k", "l", "m", "n"])
cats = pd.Series(["a", "b", "b", "b", "c", "c", "c"], dtype="category", index=idx)
values = [1, 2, 2, 2, 3, 4, 5]
df = pd.DataFrame({"cats": cats, "values": values}, index=idx)
df

  cats  values
h    a       1
i    b       2
j    b       2
k    b       2
l    c       3
m    c       4
n    c       5

In [68]:
df.iloc[2:4, :]

  cats  values
j    b       2
k    b       2

In [69]:
df.iloc[2:4, :].dtypes

cats      category
values       int64
dtype: object

In [70]:
df.loc["h":"j", "cats"]

h    a
i    b
j    b
Name: cats, dtype: category
Categories (3, object): ['a', 'b', 'c']

## String and Datetime Accessors

In [71]:
str_s = pd.Series(list("aabb"))
str_cat = str_s.astype("category")

str_cat

0    a
1    a
2    b
3    b
dtype: category
Categories (2, object): ['a', 'b']

In [72]:
str_cat.str.contains("a")

0     True
1     True
2    False
3    False
dtype: bool

In [73]:
date_s = pd.Series(pd.date_range("1/1/2015", periods=5))
date_cat = date_s.astype("category")
date_cat

0   2015-01-01
1   2015-01-02
2   2015-01-03
3   2015-01-04
4   2015-01-05
dtype: category
Categories (5, datetime64[ns]): [2015-01-01, 2015-01-02, 2015-01-03, 2015-01-04, 2015-01-05]

In [74]:
date_cat.dt.day

0    1
1    2
2    3
3    4
4    5
dtype: int32

## Setting

In [75]:
# To set a value in a categorical Series, the value must be included in the categories
idx = pd.Index(["h", "i", "j", "k", "l", "m", "n"])
cats = pd.Categorical(["a", "a", "a", "a", "a", "a", "a"], categories=["a", "b"])
values = [1, 1, 1, 1, 1, 1, 1]
df = pd.DataFrame({"cats": cats, "values": values}, index=idx)
df

  cats  values
h    a       1
i    a       1
j    a       1
k    a       1
l    a       1
m    a       1
n    a       1

In [76]:
df.iloc[2:4, :] = [["b", 2], ["b", 2]]
df

  cats  values
h    a       1
i    a       1
j    b       2
k    b       2
l    a       1
m    a       1
n    a       1

In [77]:
# Value "c" is not included in "categories", so it raises:
try:
    df.iloc[2:4, :] = [["c", 3], ["c", 3]]
except TypeError as e:
    print("TypeError", str(e))

TypeError Cannot setitem on a Categorical with a new category, set the categories first

## Merging / Concatenation

In [78]:
from pandas.api.types import union_categoricals

# same categories
s1 = pd.Series(["a", "b"], dtype="category")
s2 = pd.Series(["a", "b", "a"], dtype="category")
pd.concat([s1, s2])

0    a
1    b
0    a
1    b
2    a
dtype: category
Categories (2, object): ['a', 'b']

In [79]:
# different categories: the results now are "object" and not "category"
s3 = pd.Series(["b", "c"], dtype="category")
pd.concat([s1, s3])

0    a
1    b
0    b
1    c
dtype: object

In [80]:
# output type is inferred based on categories values
int_cats = pd.Series([1, 2], dtype="category")
float_cats = pd.Series([3.0, 4.0], dtype="category")
pd.concat([int_cats, float_cats])

0    1.0
1    2.0
0    3.0
1    4.0
dtype: float64

In [81]:
union_categoricals([s1.array, s3.array])

['a', 'b', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']

## Unioning

In [82]:
# To combine categoricals that don't necessarily have the same categories:
from pandas.api.types import union_categoricals

a = pd.Categorical(["b", "c"])
b = pd.Categorical(["a", "b"])

# Return the union of the categories as a list:
union_categoricals([a, b])

['b', 'c', 'a', 'b']
Categories (3, object): ['b', 'c', 'a']

In [83]:
# For lexical sorting of the categories:
union_categoricals([a, b], sort_categories=True)

['b', 'c', 'a', 'b']
Categories (3, object): ['a', 'b', 'c']

In [84]:
a = pd.Categorical(["a", "b"], ordered=True)
b = pd.Categorical(["a", "b", "a"], ordered=True)

union_categoricals([a, b])

['a', 'b', 'a', 'b', 'a']
Categories (2, object): ['a' < 'b']

In [85]:
# For not identical but ordered categories, an error is raised:
try:
    a = pd.Categorical(["a", "b"], ordered=True)
    b = pd.Categorical(["a", "b", "c"], ordered=True)
    union_categoricals([a, b])
except TypeError as e:
    print("TypeError: ", str(e))

TypeError:  to union ordered Categoricals, all categories must be the same

In [86]:
# To avoid the above error, use ignore_ordered=True:
a = pd.Categorical(["a", "b"], ordered=True)
b = pd.Categorical(["a", "b", "c"], ordered=True)
union_categoricals([a, b], ignore_order=True)

['a', 'b', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']

In [87]:
a = pd.Series(["b", "c"], dtype="category")
b = pd.Series(["a", "b"], dtype="category")

union_categoricals([a, b])

['b', 'c', 'a', 'b']
Categories (3, object): ['b', 'c', 'a']

# Getting Data In/Out

In [92]:
# If we write and later read back data from a .csv file, we must convert the
# relevant columns back to "category"
import io

s = pd.Series(pd.Categorical(["a", "b", "b", "a", "a", "d"]))

# Rename the categories
s = s.cat.rename_categories(["very good", "good", "bad"])

# Re-order the categories and add missing categories
s = s.cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

df = pd.DataFrame({"cats": s, "vals": [1, 2, 3, 4, 5, 6]})

csv = io.StringIO()
df.to_csv(csv)  # convert to CSV but in memory
df2 = pd.read_csv(io.StringIO(csv.getvalue()))
df2.dtypes

Unnamed: 0     int64
cats          object
vals           int64
dtype: object

In [ ]:
# The "cats" column, when read from the CSV, is no longer of "category" dtype
df2["cats"]

0    very good
1         good
2         good
3    very good
4    very good
5          bad
Name: cats, dtype: object

In [94]:
# Redo the category
df2["cats"] = df2["cats"].astype("category")

# Re-order and set missing categories
df2["cats"] = df2["cats"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

# Now check the dtype
df2.dtypes

Unnamed: 0       int64
cats          category
vals             int64
dtype: object

# Missing Data

In [97]:
s = pd.Series(["a", "b", np.nan, "a"], dtype="category")

# only two categories
s

0      a
1      b
2    NaN
3      a
dtype: category
Categories (2, object): ['a', 'b']

In [ ]:
# Missing values always have code = -1
s.cat.codes

0    0
1    1
2   -1
3    0
dtype: int8

In [99]:
s = pd.Series(["a", "b", np.nan], dtype="category")

pd.isna(s)

0    False
1    False
2     True
dtype: bool

In [100]:
s.fillna("a")

0    a
1    b
2    a
dtype: category
Categories (2, object): ['a', 'b']

# Memory Usage

In [101]:
s = pd.Series(["foo", "bar"] * 1000)

# object dtype
s.nbytes

16000

In [102]:
# category dtype
s.astype("category").nbytes

2016

In [103]:
s = pd.Series(["foo%04d" % i for i in range(2000)])

# object dtype
s.nbytes

16000

In [ ]:
# category dtype
# here number of categories is very high (2000) same as length of data
s.astype("category").nbytes

20000

# Categorical is not a `numpy` array

In [107]:
try:
    np.dtype("category")
except TypeError as e:
    print("TypeError: ", str(e))
    print("NumPy does not know anything about the new 'category' dtype")

TypeError:  data type 'category' not understood
NumPy does not know anything about the new 'category' dtype

In [108]:
dtype = pd.Categorical(["a"]).dtype

try:
    np.dtype(dtype)
except TypeError as e:
    print("TypeError: ", str(e))

TypeError:  Cannot interpret 'CategoricalDtype(categories=['a'], ordered=False, categories_dtype=object)' as a data type

In [110]:
dtype == np.str_

False

In [111]:
# Check if a Series has Categorical data:
hasattr(pd.Series(["a"], dtype="category"), "cat")

True

# dtype in apply