In [2]:
# Parsing time series information from various sources and formats
import datetime
import numpy as np
import pandas as pd

dti = pd.to_datetime(
    [
        "1/1/2018",
        np.datetime64("2018-01-01"),
        datetime.datetime(2018, 1, 1),
    ]
)

dti

DatetimeIndex(['2018-01-01', '2018-01-01', '2018-01-01'], dtype='datetime64[us]', freq=None)

In [3]:
# Generate sequences of fixed frequency dates and time spans
dti = pd.date_range("2018-01-01", periods=3, freq="h")
dti

DatetimeIndex(['2018-01-01 00:00:00', '2018-01-01 01:00:00',
               '2018-01-01 02:00:00'],
              dtype='datetime64[us]', freq='h')

In [4]:
# Manipulating and converting date times with timezone information
dti = dti.tz_localize("UTC")
dti

DatetimeIndex(['2018-01-01 00:00:00+00:00', '2018-01-01 01:00:00+00:00',
               '2018-01-01 02:00:00+00:00'],
              dtype='datetime64[us, UTC]', freq='h')

In [5]:
dti.tz_convert("US/Pacific")

DatetimeIndex(['2017-12-31 16:00:00-08:00', '2017-12-31 17:00:00-08:00',
               '2017-12-31 18:00:00-08:00'],
              dtype='datetime64[us, US/Pacific]', freq='h')

In [6]:
# Resampling or converting a series to a particular frequency
idx = pd.date_range("2018-01-01", periods=5, freq="h")
ts = pd.Series(range(len(idx)), index=idx)
ts

2018-01-01 00:00:00    0
2018-01-01 01:00:00    1
2018-01-01 02:00:00    2
2018-01-01 03:00:00    3
2018-01-01 04:00:00    4
Freq: h, dtype: int64

In [7]:
# Downsample the series into 2h bins, and average the
# values of the timestamps falling into the bins:
ts.resample("2h").mean()

2018-01-01 00:00:00    0.5
2018-01-01 02:00:00    2.5
2018-01-01 04:00:00    4.0
Freq: 2h, dtype: float64

In [8]:
# Performing date and time arithmetic, with absolute or relative time increments:
friday = pd.Timestamp("2018-01-05")
friday.day_name()

'Friday'

In [9]:
# Add 1 day
saturday = friday + pd.Timedelta("1 day")

saturday.day_name()

'Saturday'

In [10]:
# Add 1 business day (Friday -> Monday)
monday = friday + pd.offsets.BDay()

monday.day_name()

'Monday'

# Overview

In [11]:
# It's best to represent the time component as the index of a Series/DataFrame
pd.Series(range(3), index=pd.date_range("2000", freq="D", periods=3))

2000-01-01    0
2000-01-02    1
2000-01-03    2
Freq: D, dtype: int64

In [12]:
# But can also use it as data itself
pd.Series(pd.date_range("2000", freq="D", periods=3))

0   2000-01-01
1   2000-01-02
2   2000-01-03
dtype: datetime64[us]

In [13]:
pd.Series(pd.period_range("1/1/2011", freq="M", periods=3))

0    2011-01
1    2011-02
2    2011-03
dtype: period[M]

In [14]:
pd.Series([pd.DateOffset(1), pd.DateOffset(2)])

0         <DateOffset>
1    <2 * DateOffsets>
dtype: object

In [15]:
pd.Series(pd.date_range("1/1/2011", freq="ME", periods=3))

0   2011-01-31
1   2011-02-28
2   2011-03-31
dtype: datetime64[us]

In [16]:
# Null datetimes are represented as NaT
pd.Timestamp(pd.NaT)

NaT

In [17]:
pd.Timedelta(pd.NaT)

NaT

In [18]:
pd.Period(pd.NaT)

NaT

In [19]:
# Equality acts as np.nan would do
pd.NaT == pd.NaT

False

# Timestamps vs. Time Spans

In [20]:
import datetime

# from a string
pd.Timestamp("2012-05-01")

Timestamp('2012-05-01 00:00:00')

In [21]:
# from arguments
pd.Timestamp(2012, 5, 1)

Timestamp('2012-05-01 00:00:00')

In [22]:
# from a datetime object
pd.Timestamp(datetime.datetime(2012, 5, 1))

Timestamp('2012-05-01 00:00:00')

In [23]:
# The time span is inferred from the date string (month)
pd.Period("2011-01")

Period('2011-01', 'M')

In [24]:
pd.Period("2012-05", freq="D")

Period('2012-05-01', 'D')

In [25]:
# A list of Timestamps, is automatically coerced into a DatetimeIndex
dates = [
    pd.Timestamp("2012-05-01"),
    pd.Timestamp("2012-05-02"),
    pd.Timestamp("2012-05-03"),
]

ts = pd.Series(np.random.randn(3), dates)

In [26]:
type(ts.index)

pandas.DatetimeIndex

In [27]:
ts.index

DatetimeIndex(['2012-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[us]', freq=None)

In [28]:
ts

2012-05-01   -0.235034
2012-05-02   -0.638592
2012-05-03    0.835220
dtype: float64

In [29]:
periods = [pd.Period("2012-01"), pd.Period("2012-02"), pd.Period("2012-03")]
ts = pd.Series(np.random.randn(3), periods)

type(ts.index)

pandas.PeriodIndex

In [30]:
ts.index

PeriodIndex(['2012-01', '2012-02', '2012-03'], dtype='period[M]')

In [31]:
ts

2012-01    1.249380
2012-02   -0.023586
2012-03   -0.500652
Freq: M, dtype: float64

# Converting to Timestamps

In [32]:
# When passed a Series, it returns a Series of datetime objects
pd.to_datetime(pd.Series(["Jul 31, 2009", "Jan 10, 2010", None]))

0   2009-07-31
1   2010-01-10
2          NaT
dtype: datetime64[us]

In [33]:
# If passed a list, it returns a DatetimeIndex
pd.to_datetime(["2005/11/23", "2010/12/31"])

DatetimeIndex(['2005-11-23', '2010-12-31'], dtype='datetime64[us]', freq=None)

## Using European date style
Just pass the `dayfirst=True` flag

In [34]:
pd.to_datetime(["04/01/2012 10:00"], dayfirst=True)

DatetimeIndex(['2012-01-04 10:00:00'], dtype='datetime64[us]', freq=None)

In [35]:
# Directly construct a DatetimeIndex
pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"])

DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05'], dtype='datetime64[us]', freq=None)

In [36]:
pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"], freq="infer")

DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05'], dtype='datetime64[us]', freq='2D')

## Providing a format argument

In [37]:
pd.to_datetime("2010/11/12", format="%Y/%m/%d")

Timestamp('2010-11-12 00:00:00')

In [38]:
pd.to_datetime("29/11/1964", format="%d/%m/%Y")

Timestamp('1964-11-29 00:00:00')

## Assembling datetime from multiple DataFrame columns

In [39]:
df = pd.DataFrame(
    {
        "year": [2015, 2016],
        "month": [2, 3],
        "day": [4, 5],
        "hour": [2, 3],
    }
)

pd.to_datetime(df)

0   2015-02-04 02:00:00
1   2016-03-05 03:00:00
dtype: datetime64[us]

In [40]:
# Or choose which columns to pass
pd.to_datetime(df[["year", "month", "day"]])

0   2015-02-04
1   2016-03-05
dtype: datetime64[us]

## Invalid data

The default `errors="raise"`, will raise an exception if the string cannot be parsed

In [41]:
pd.to_datetime(["2009/07/31", "asd"], errors="raise")

ValueError: time data "asd" doesn't match format "%Y/%m/%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
# To convert unparsable strings to NaT (Not a Time):
pd.to_datetime(["2009/07/31", "asd"], errors="coerce")

DatetimeIndex(['2009-07-31', 'NaT'], dtype='datetime64[us]', freq=None)

## Epoch Timestamps

## Using the `origin` parameter

In [42]:
# Specify 1-Jan-1906 as the starting date:
pd.to_datetime([1, 2, 3], unit="D", origin=pd.Timestamp("1960-01-01"))

DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'], dtype='datetime64[s]', freq=None)

In [43]:
# Default is oring='unix' i.e. the 'unix epoch'
pd.to_datetime([1, 2, 3], unit="D")

DatetimeIndex(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[s]', freq=None)

# Generating ranges of timestamps

Use either:
- the DatetimeIndex or the
- Index object

In [44]:
dates = [
    datetime.datetime(2012, 5, 1),
    datetime.datetime(2012, 5, 2),
    datetime.datetime(2012, 5, 3),
]

# Note the frequency information
index = pd.DatetimeIndex(dates)
index

DatetimeIndex(['2012-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[us]', freq=None)

In [45]:
# Automatically converted to DatetimeIndex
index = pd.Index(dates)
index

DatetimeIndex(['2012-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[us]', freq=None)

In [46]:
start = pd.Timestamp(2011, 1, 1)
end = pd.Timestamp(2012, 1, 1)

# DatetimeIndex of calendar dates: freq="D"
index = pd.date_range(start, end)
index

DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10',
               ...
               '2011-12-23', '2011-12-24', '2011-12-25', '2011-12-26',
               '2011-12-27', '2011-12-28', '2011-12-29', '2011-12-30',
               '2011-12-31', '2012-01-01'],
              dtype='datetime64[us]', length=366, freq='D')

In [47]:
# DatetimeIndex of business days: freq="B"
index = pd.bdate_range(start, end)
index

DatetimeIndex(['2011-01-03', '2011-01-04', '2011-01-05', '2011-01-06',
               '2011-01-07', '2011-01-10', '2011-01-11', '2011-01-12',
               '2011-01-13', '2011-01-14',
               ...
               '2011-12-19', '2011-12-20', '2011-12-21', '2011-12-22',
               '2011-12-23', '2011-12-26', '2011-12-27', '2011-12-28',
               '2011-12-29', '2011-12-30'],
              dtype='datetime64[us]', length=260, freq='B')

In [48]:
# DatetimeIndex of calendar month-ends: freq="ME"
pd.date_range(start, periods=1000, freq="ME")

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30',
               '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31',
               '2011-09-30', '2011-10-31',
               ...
               '2093-07-31', '2093-08-31', '2093-09-30', '2093-10-31',
               '2093-11-30', '2093-12-31', '2094-01-31', '2094-02-28',
               '2094-03-31', '2094-04-30'],
              dtype='datetime64[us]', length=1000, freq='ME')

In [49]:
# Quarters: freq="BQS" start of quarter
pd.date_range(start, periods=250, freq="BQS")

DatetimeIndex(['2011-01-03', '2011-04-01', '2011-07-01', '2011-10-03',
               '2012-01-02', '2012-04-02', '2012-07-02', '2012-10-01',
               '2013-01-01', '2013-04-01',
               ...
               '2071-01-01', '2071-04-01', '2071-07-01', '2071-10-01',
               '2072-01-01', '2072-04-01', '2072-07-01', '2072-10-03',
               '2073-01-02', '2073-04-03'],
              dtype='datetime64[us]', length=250, freq='BQS-JAN')

In [50]:
# Business month-end
pd.date_range(start, end, freq="BME")

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-29',
               '2011-05-31', '2011-06-30', '2011-07-29', '2011-08-31',
               '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-30'],
              dtype='datetime64[us]', freq='BME')

In [51]:
# Week range
pd.date_range(start, end, freq="W")

DatetimeIndex(['2011-01-02', '2011-01-09', '2011-01-16', '2011-01-23',
               '2011-01-30', '2011-02-06', '2011-02-13', '2011-02-20',
               '2011-02-27', '2011-03-06', '2011-03-13', '2011-03-20',
               '2011-03-27', '2011-04-03', '2011-04-10', '2011-04-17',
               '2011-04-24', '2011-05-01', '2011-05-08', '2011-05-15',
               '2011-05-22', '2011-05-29', '2011-06-05', '2011-06-12',
               '2011-06-19', '2011-06-26', '2011-07-03', '2011-07-10',
               '2011-07-17', '2011-07-24', '2011-07-31', '2011-08-07',
               '2011-08-14', '2011-08-21', '2011-08-28', '2011-09-04',
               '2011-09-11', '2011-09-18', '2011-09-25', '2011-10-02',
               '2011-10-09', '2011-10-16', '2011-10-23', '2011-10-30',
               '2011-11-06', '2011-11-13', '2011-11-20', '2011-11-27',
               '2011-12-04', '2011-12-11', '2011-12-18', '2011-12-25',
               '2012-01-01'],
              dtype='datetime64[us]', freq='W-SUN')

In [52]:
# Twenty days ending on 1-Jan-2012
pd.bdate_range(end=end, periods=20)

DatetimeIndex(['2011-12-06', '2011-12-07', '2011-12-08', '2011-12-09',
               '2011-12-12', '2011-12-13', '2011-12-14', '2011-12-15',
               '2011-12-16', '2011-12-19', '2011-12-20', '2011-12-21',
               '2011-12-22', '2011-12-23', '2011-12-26', '2011-12-27',
               '2011-12-28', '2011-12-29', '2011-12-30'],
              dtype='datetime64[us]', freq='B')

## Custom Frequency Ranges

In [53]:
weekmask = "Mon Wed Fri"
holidays = [datetime.datetime(2011, 1, 5), datetime.datetime(2011, 3, 14)]
pd.bdate_range(start, end, freq="C", weekmask=weekmask, holidays=holidays)

DatetimeIndex(['2011-01-03', '2011-01-07', '2011-01-10', '2011-01-12',
               '2011-01-14', '2011-01-17', '2011-01-19', '2011-01-21',
               '2011-01-24', '2011-01-26',
               ...
               '2011-12-09', '2011-12-12', '2011-12-14', '2011-12-16',
               '2011-12-19', '2011-12-21', '2011-12-23', '2011-12-26',
               '2011-12-28', '2011-12-30'],
              dtype='datetime64[us]', length=154, freq='C')

In [54]:
pd.Timestamp(2011, 1, 3).day_name()

'Monday'

# Timestamp Limitations

In [55]:
# For nanosecond resolution, the the time stamp range is ~584 years:
print(f"{pd.Timestamp.min.year} - {pd.Timestamp.max.year}")

1677 - 2262

# Indexing

A DatetimeIndex offers all of its intelligent functionality like selection, slicing etc.

In [56]:
rng = pd.date_range(start, end, freq="BME")
ts = pd.Series(np.random.randn(len(rng)), index=rng)

ts.index

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-29',
               '2011-05-31', '2011-06-30', '2011-07-29', '2011-08-31',
               '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-30'],
              dtype='datetime64[us]', freq='BME')

In [57]:
ts[:5].index

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-29',
               '2011-05-31'],
              dtype='datetime64[us]', freq='BME')

In [58]:
ts[::2].index

DatetimeIndex(['2011-01-31', '2011-03-31', '2011-05-31', '2011-07-29',
               '2011-09-30', '2011-11-30'],
              dtype='datetime64[us]', freq='2BME')

## Partial String Indexing

In [59]:
ts["1/31/2011"]

np.float64(-1.3940876783696572)

In [60]:
ts[datetime.datetime(2011, 12, 25) :]

2011-12-30    0.037182
Freq: BME, dtype: float64

In [61]:
ts["10/31/2011":"12/31/2011"]

2011-10-31   -0.531176
2011-11-30   -0.570391
2011-12-30    0.037182
Freq: BME, dtype: float64

In [62]:
ts["2011"]

2011-01-31   -1.394088
2011-02-28   -0.574791
2011-03-31   -0.457196
2011-04-29   -0.117564
2011-05-31    0.023470
2011-06-30   -0.477179
2011-07-29    1.282897
2011-08-31    0.735920
2011-09-30   -0.199748
2011-10-31   -0.531176
2011-11-30   -0.570391
2011-12-30    0.037182
Freq: BME, dtype: float64

In [63]:
ts["2011-6"]

2011-06-30   -0.477179
Freq: BME, dtype: float64

In [64]:
# For a DataFrame, in order to index with a date string, use loc indexer
dft = pd.DataFrame(
    np.random.randn(100_000, 1),
    columns=["A"],
    index=pd.date_range("20130101", periods=100_000, freq="min"),
)

dft

                            A
2013-01-01 00:00:00  0.056222
2013-01-01 00:01:00  0.349712
2013-01-01 00:02:00 -0.454922
2013-01-01 00:03:00 -0.062371
2013-01-01 00:04:00 -0.316073
...                       ...
2013-03-11 10:35:00 -0.341474
2013-03-11 10:36:00 -1.018341
2013-03-11 10:37:00 -0.542406
2013-03-11 10:38:00  1.080732
2013-03-11 10:39:00  1.068042

[100000 rows x 1 columns]

In [65]:
dft.loc["2013"]

                            A
2013-01-01 00:00:00  0.056222
2013-01-01 00:01:00  0.349712
2013-01-01 00:02:00 -0.454922
2013-01-01 00:03:00 -0.062371
2013-01-01 00:04:00 -0.316073
...                       ...
2013-03-11 10:35:00 -0.341474
2013-03-11 10:36:00 -1.018341
2013-03-11 10:37:00 -0.542406
2013-03-11 10:38:00  1.080732
2013-03-11 10:39:00  1.068042

[100000 rows x 1 columns]

In [66]:
# Start from the first day of Jan up to the last day of Feb
dft["2013-1":"2013-2"]

                            A
2013-01-01 00:00:00  0.056222
2013-01-01 00:01:00  0.349712
2013-01-01 00:02:00 -0.454922
2013-01-01 00:03:00 -0.062371
2013-01-01 00:04:00 -0.316073
...                       ...
2013-02-28 23:55:00  0.885295
2013-02-28 23:56:00 -0.206114
2013-02-28 23:57:00  1.699135
2013-02-28 23:58:00  2.246188
2013-02-28 23:59:00 -0.410303

[84960 rows x 1 columns]

In [67]:
# Also, works on a MultiIndex
dft2 = pd.DataFrame(
    np.random.randn(20, 1),
    columns=["A"],
    index=pd.MultiIndex.from_product(
        [
            pd.date_range("20130101", periods=10, freq="12h"),
            ["a", "b"],
        ],
    ),
)

dft2

                              A
2013-01-01 00:00:00 a -0.086255
                    b  0.954005
2013-01-01 12:00:00 a  0.530556
                    b  1.570593
2013-01-02 00:00:00 a -1.326847
                    b -2.019855
2013-01-02 12:00:00 a  3.036623
                    b  0.093628
2013-01-03 00:00:00 a  0.985045
                    b  2.134165
2013-01-03 12:00:00 a  0.675370
                    b -0.715778
2013-01-04 00:00:00 a  1.183021
                    b -0.657424
2013-01-04 12:00:00 a  0.376956
                    b -0.502373
2013-01-05 00:00:00 a  0.789478
                    b -0.037625
2013-01-05 12:00:00 a  0.689246
                    b -1.285770

In [68]:
dft2.loc["2013-01-05"]

                              A
2013-01-05 00:00:00 a  0.789478
                    b -0.037625
2013-01-05 12:00:00 a  0.689246
                    b -1.285770

In [69]:
idx = pd.IndexSlice
dft2 = dft2.swaplevel(0, 1).sort_index()
dft2.loc[idx[:, "2013-01-05"], :]

                              A
a 2013-01-05 00:00:00  0.789478
  2013-01-05 12:00:00  0.689246
b 2013-01-05 00:00:00 -0.037625
  2013-01-05 12:00:00 -1.285770

## Slice vs. Exact Match

In [70]:
# A Series with a minute resolution-index:
series_minute = pd.Series(
    [1, 2, 3],
    pd.DatetimeIndex(["2011-12-31 23:59:00", "2012-01-01 00:00:00", "2012-01-01 00:02:00"]),
)

series_minute.index.resolution

'minute'

In [71]:
series_minute["2011-12-31 23"]

2011-12-31 23:59:00    1
dtype: int64

In [72]:
series_minute["2011-12-31 23:59"]

np.int64(1)

## Exact Indexing

In [73]:
dft[datetime.datetime(2013, 1, 1) : datetime.datetime(2013, 2, 28)]

                            A
2013-01-01 00:00:00  0.056222
2013-01-01 00:01:00  0.349712
2013-01-01 00:02:00 -0.454922
2013-01-01 00:03:00 -0.062371
2013-01-01 00:04:00 -0.316073
...                       ...
2013-02-27 23:56:00 -1.038569
2013-02-27 23:57:00  0.315946
2013-02-27 23:58:00  0.891048
2013-02-27 23:59:00 -0.879315
2013-02-28 00:00:00 -0.369863

[83521 rows x 1 columns]

## Truncating and Fancy Indexing

In [74]:
rng2 = pd.date_range("2011-01-01", "2012-01-01", freq="W")
ts2 = pd.Series(np.random.randn(len(rng2)), index=rng2)
ts2.truncate(before="2011-11", after="2011-12")

2011-11-06   -0.601863
2011-11-13   -0.075989
2011-11-20    0.679146
2011-11-27   -0.420886
Freq: W-SUN, dtype: float64

# Time/Date Components

# DateOffset Objects

In [75]:
# This particular day contains a day light savings time transition
ts = pd.Timestamp("2016-10-30 00:00:00", tz="Europe/Helsinki")

In [76]:
# Respects absolute time
ts + pd.Timedelta(days=1)

Timestamp('2016-10-30 23:00:00+0200', tz='Europe/Helsinki')

In [77]:
# Respects calendar time
ts + pd.DateOffset(days=1)

Timestamp('2016-10-31 00:00:00+0200', tz='Europe/Helsinki')

In [78]:
friday = pd.Timestamp("2018-01-05")
friday.day_name()

'Friday'

In [79]:
# Add 2 business days (Fri --> Tue)
two_business_days = 2 * pd.offsets.BDay()

friday + two_business_days

Timestamp('2018-01-09 00:00:00')

In [80]:
(friday + two_business_days).day_name()

'Tuesday'

## Parametric Offsets

In [81]:
d = datetime.datetime(2008, 8, 18, 9, 0)
d

datetime.datetime(2008, 8, 18, 9, 0)

In [ ]:
# Offset by 7 days (18+7=25)
d + pd.offsets.Week()

Timestamp('2008-08-25 09:00:00')

In [ ]:
# Offset by a week but end up on day 4 of the week (18+4=22)
d + pd.offsets.Week(weekday=4)

Timestamp('2008-08-22 09:00:00')

In [84]:
(d + pd.offsets.Week(weekday=4)).weekday()

4

In [85]:
d - pd.offsets.Week()

Timestamp('2008-08-11 09:00:00')

In [ ]:
# Reset time to 00:00
d + pd.offsets.Week(normalize=True)

Timestamp('2008-08-25 00:00:00')

In [ ]:
# Move to the end of the year
d + pd.offsets.YearEnd()

Timestamp('2008-12-31 09:00:00')

## Using offsets with Series/DatetimeIndex

In [88]:
rng = pd.date_range("2012-01-01", "2012-01-03")
s = pd.Series(rng)
rng

DatetimeIndex(['2012-01-01', '2012-01-02', '2012-01-03'], dtype='datetime64[us]', freq='D')

In [89]:
rng + pd.DateOffset(months=2)

DatetimeIndex(['2012-03-01', '2012-03-02', '2012-03-03'], dtype='datetime64[us]', freq=None)

In [90]:
s + pd.DateOffset(months=2)

0   2012-03-01
1   2012-03-02
2   2012-03-03
dtype: datetime64[us]

In [91]:
s - pd.offsets.Day(2)

0   2011-12-30
1   2011-12-31
2   2012-01-01
dtype: datetime64[us]

In [92]:
td = s - pd.Series(pd.date_range("2011-12-29", "2011-12-31"))
td

0   3 days
1   3 days
2   3 days
dtype: timedelta64[us]

## Custom Business Days

In [96]:
# In Egypt a Friday-Saturday weekend is observed
weekmask_egypt = "Sun Mon Tue Wed Thu"

# They alos observe International Worker's Day so let's add that for a couple of years
holidays = [
    "2012-05-01",
    datetime.datetime(2013, 5, 1),
    np.datetime64("2014-05-01"),
]

bday_egypt = pd.offsets.CustomBusinessDay(holidays=holidays, weekmask=weekmask_egypt)
dt = datetime.datetime(2013, 4, 30)
dt + 2 * bday_egypt

Timestamp('2013-05-05 00:00:00')

In [97]:
# Map to the weekday names:
dts = pd.date_range(dt, periods=5, freq=bday_egypt)
pd.Series(dts.weekday, dts).map(pd.Series("Mon Tue Wed Thu Fri Sat Sun".split()))

2013-04-30    Tue
2013-05-02    Thu
2013-05-05    Sun
2013-05-06    Mon
2013-05-07    Tue
Freq: C, dtype: str

In [98]:
from pandas.tseries.holiday import USFederalHolidayCalendar

bday_us = pd.offsets.CustomBusinessDay(calendar=USFederalHolidayCalendar())

# Friday before MLK Day
dt = datetime.datetime(2014, 1, 17)

# Tuesday after MLK Day (Monday is skipped because it's a holiday)
dt + bday_us

Timestamp('2014-01-21 00:00:00')

## Business Hour

In [99]:
bh = pd.offsets.BusinessHour()
bh

In [100]:
# 2014-08-01 is Friday
pd.Timestamp("2014-08-01 10:00").weekday()

4

In [101]:
pd.Timestamp("2014-08-01 10:00") + bh

Timestamp('2014-08-01 11:00:00')

# Time Series-related Instance Methods
## Shifting/Lagging

In [102]:
ts = pd.Series(range(len(rng)), index=rng)
ts

2012-01-01    0
2012-01-02    1
2012-01-03    2
Freq: D, dtype: int64

In [ ]:
ts = ts[:5]

# Shift the values forward
ts.shift(1)

2012-01-01    NaN
2012-01-02    0.0
2012-01-03    1.0
Freq: D, dtype: float64

In [105]:
# Now change the dates in the index
ts.shift(5, freq="D")

2012-01-06    0
2012-01-07    1
2012-01-08    2
Freq: D, dtype: int64

## Frequency Conversion

In [107]:
dr = pd.date_range("1/1/2010", periods=3, freq=3 * pd.offsets.BDay())
ts = pd.Series(np.random.randn(3), index=dr)
ts

2010-01-01   -0.706802
2010-01-06   -0.762440
2010-01-11   -1.391620
Freq: 3B, dtype: float64

In [108]:
ts.asfreq(pd.offsets.BDay())

2010-01-01   -0.706802
2010-01-04         NaN
2010-01-05         NaN
2010-01-06   -0.762440
2010-01-07         NaN
2010-01-08         NaN
2010-01-11   -1.391620
Freq: B, dtype: float64

# Resampling
## Basics: Resampling means frequency conversion

In [122]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts.resample("5min").sum()

2012-01-01    25335
Freq: 5min, dtype: int32

In [123]:
ts.resample("5min").mean()

2012-01-01    253.35
Freq: 5min, dtype: float64

In [124]:
ts.resample("5min").ohlc()

            open  high  low  close
2012-01-01   148   495    2    172

In [125]:
ts.resample("5min").max()

2012-01-01    495
Freq: 5min, dtype: int32

In [ ]:
# Specify that the right side of the bin interval is closed
ts.resample("5min", closed="right").mean()

2011-12-31 23:55:00    148.000000
2012-01-01 00:00:00    254.414141
Freq: 5min, dtype: float64

In [127]:
# Specify that the left side of the bin interval is closed
ts.resample("5min", closed="left").mean()

2012-01-01    253.35
Freq: 5min, dtype: float64

## Upsampling

In [ ]:
# From secondly to every 250 ms
# Use only the first two values of the original Series i.e. at 00:00:00 and 00:00:01 seconds
# Then upsample to 250ms
ts[:2].resample("250ms").asfreq()

2012-01-01 00:00:00.000    148.0
2012-01-01 00:00:00.250      NaN
2012-01-01 00:00:00.500      NaN
2012-01-01 00:00:00.750      NaN
2012-01-01 00:00:01.000    413.0
Freq: 250ms, dtype: float64

In [129]:
# Forward fill with the last non-null value
ts[:2].resample("250ms").ffill()

2012-01-01 00:00:00.000    148
2012-01-01 00:00:00.250    148
2012-01-01 00:00:00.500    148
2012-01-01 00:00:00.750    148
2012-01-01 00:00:01.000    413
Freq: 250ms, dtype: int32

In [130]:
ts[:2].resample("250ms").ffill(limit=2)

2012-01-01 00:00:00.000    148.0
2012-01-01 00:00:00.250    148.0
2012-01-01 00:00:00.500    148.0
2012-01-01 00:00:00.750      NaN
2012-01-01 00:00:01.000    413.0
Freq: 250ms, dtype: float64

## Sparse Resampling

In [136]:
rng = pd.date_range("2014-1-1", periods=100, freq="D") + pd.Timedelta("1s")
ts = pd.Series(range(100), index=rng)
ts

2014-01-01 00:00:01     0
2014-01-02 00:00:01     1
2014-01-03 00:00:01     2
2014-01-04 00:00:01     3
2014-01-05 00:00:01     4
                       ..
2014-04-06 00:00:01    95
2014-04-07 00:00:01    96
2014-04-08 00:00:01    97
2014-04-09 00:00:01    98
2014-04-10 00:00:01    99
Freq: D, Length: 100, dtype: int64

In [137]:
# Resample to the full range of the series
ts.resample("3min").sum()

2014-01-01 00:00:00     0
2014-01-01 00:03:00     0
2014-01-01 00:06:00     0
2014-01-01 00:09:00     0
2014-01-01 00:12:00     0
                       ..
2014-04-09 23:48:00     0
2014-04-09 23:51:00     0
2014-04-09 23:54:00     0
2014-04-09 23:57:00     0
2014-04-10 00:00:00    99
Freq: 3min, Length: 47521, dtype: int64

In [139]:
# Only resample to those groups where we have points
from functools import partial
from pandas.tseries.frequencies import to_offset


def round(t, freq):
    freq = to_offset(freq)
    td = pd.Timedelta(freq)

    return pd.Timestamp((t.value // td.value) * td.value)


ts.groupby(partial(round, freq="3min")).sum()

2014-01-01     0
2014-01-02     1
2014-01-03     2
2014-01-04     3
2014-01-05     4
              ..
2014-04-06    95
2014-04-07    96
2014-04-08    97
2014-04-09    98
2014-04-10    99
Length: 100, dtype: int64

## Aggregation

In [140]:
# Resampling a DataFrame acts on all columns
df = pd.DataFrame(
    np.random.randn(1000, 3),
    index=pd.date_range("1/1/2012", freq="s", periods=1000),
    columns=["A", "B", "C"],
)
df

                            A         B         C
2012-01-01 00:00:00 -2.342561 -0.416088 -0.610338
2012-01-01 00:00:01  0.410880 -1.246732  1.917844
2012-01-01 00:00:02 -0.920170 -0.102008  1.736445
2012-01-01 00:00:03 -0.017328  0.777086 -0.641408
2012-01-01 00:00:04  1.500514 -0.710903 -1.218626
...                       ...       ...       ...
2012-01-01 00:16:35 -0.392706 -1.373339  0.829521
2012-01-01 00:16:36 -0.013637  0.953671  0.399787
2012-01-01 00:16:37 -0.061356 -0.057305  0.789015
2012-01-01 00:16:38  0.540731  1.911256 -2.289178
2012-01-01 00:16:39 -0.864471 -0.213089 -0.796912

[1000 rows x 3 columns]

In [141]:
r = df.resample("3min")
r.mean()

                            A         B         C
2012-01-01 00:00:00  0.082442 -0.078979  0.033385
2012-01-01 00:03:00  0.044764 -0.158862  0.107558
2012-01-01 00:06:00 -0.071036  0.135011 -0.042215
2012-01-01 00:09:00 -0.049258 -0.042530 -0.051353
2012-01-01 00:12:00 -0.047974 -0.007879  0.012207
2012-01-01 00:15:00 -0.054084 -0.016919  0.042025

## Iterating through Groups

In [145]:
small = pd.Series(
    range(6),
    index=pd.to_datetime(
        [
            "2017-01-01T00:00:00",
            "2017-01-01T00:30:00",
            "2017-01-01T00:31:00",
            "2017-01-01T01:00:00",
            "2017-01-01T03:00:00",
            "2017-01-01T03:05:00",
        ]
    ),
)

resampled = small.resample("h")

for name, group in resampled:
    print(f"Group: {name}")
    print("-" * 27)
    print(group, end="\n\n")

Group: 2017-01-01 00:00:00
---------------------------
2017-01-01 00:00:00    0
2017-01-01 00:30:00    1
2017-01-01 00:31:00    2
dtype: int64

Group: 2017-01-01 01:00:00
---------------------------
2017-01-01 01:00:00    3
dtype: int64

Group: 2017-01-01 02:00:00
---------------------------
Series([], dtype: int64)

Group: 2017-01-01 03:00:00
---------------------------
2017-01-01 03:00:00    4
2017-01-01 03:05:00    5
dtype: int64