# Idioms

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

## If-then...
An `if-then` on one column:<br/>
Return the group of rows for which the value in the "AAA" field is 5 or higher. For these rows take the "BBB" field only and make it equal to -1. Finally, return the adjusted DataFrame.

In [4]:
df.loc[df.AAA >= 5, "BBB"] = -1
df

   AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

An `if-then` with assignment to two columns

In [5]:
df.loc[df.AAA >= 5, ["BBB", "CCC"]] = 555
df

   AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

Add another line with different logic to do the `-else`

In [6]:
df.loc[df.AAA < 5, ["BBB", "CCC"]] = 2000
df

   AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

Or use pandas `where`, after you've set up a mask

In [7]:
df_mask = pd.DataFrame(
    {
        "AAA": [True] * 4,
        "BBB": [False] * 4,
        "CCC": [True, False] * 2,
    }
)

df.where(df_mask, -1000)

   AAA   BBB   CCC
0    4 -1000  2000
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

`if-then-else` using NumPy's `where`

In [8]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [9]:
df["logic"] = np.where(df.AAA > 5, "high", "low")
df

   AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

## Splitting
Split a frame with a boolean criterion

In [10]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [11]:
df[df.AAA <= 5]

   AAA  BBB  CCC
0    4   10  100
1    5   20   50

In [12]:
df[df.AAA > 5]

   AAA  BBB  CCC
2    6   30  -30
3    7   40  -50

## Building Criteria
Select with `multiple-column criteria`

In [13]:
# and
df.loc[(df.BBB < 25) & (df.CCC >= -40), "AAA"]

0    4
1    5
Name: AAA, dtype: int64

In [14]:
# or
df.loc[(df.BBB > 25) | (df.CCC >= -40), "AAA"]

0    4
1    5
2    6
3    7
Name: AAA, dtype: int64

In [15]:
# or with assignment (modifies the df)
df.loc[(df.BBB > 25) | (df.CCC >= 75), "AAA"] = 999
df

   AAA  BBB  CCC
0  999   10  100
1    5   20   50
2  999   30  -30
3  999   40  -50

Select rows with data closest to certain value using `argsort`

In [16]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [17]:
aValue = 43.0

df.loc[(df.CCC - aValue).abs().argsort()]

   AAA  BBB  CCC
1    5   20   50
0    4   10  100
2    6   30  -30
3    7   40  -50

Dynamically reduce a list of criteria using binary operators

In [18]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [19]:
Crit1 = df.AAA <= 5.5
Crit2 = df.BBB == 10.0
Crit3 = df.CCC >= -40.0

In [20]:
import functools

CritList = [Crit1, Crit2, Crit3]

# Apply a function (of two arguments) cumulatively to the items of an
# iterable, essentially reducing the iterable to a scalar value.
AllCrit = functools.reduce(lambda x, y: x & y, CritList)

df[AllCrit]

   AAA  BBB  CCC
0    4   10  100

# Selection
## DataFrames
Using both row labels, and value conditionals.

In [21]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [22]:
df[(df.AAA <= 6) & (df.index.isin([0, 2, 4]))]

   AAA  BBB  CCC
0    4   10  100
2    6   30  -30

Use `loc` for label-based slicing, and `iloc` positional slicing.

In [23]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    },
    index=["foo", "bar", "boo", "kar"],
)
df

     AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

In [24]:
df.loc["bar":"kar"]  # label-based slicing: includes last element

     AAA  BBB  CCC
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

In [25]:
df[0:3]  # generic

     AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30

In [26]:
df["bar":"kar"]

     AAA  BBB  CCC
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

In [27]:
data = {
    "AAA": [4, 5, 6, 7],
    "BBB": [10, 20, 30, 40],
    "CCC": [100, 50, -30, -50],
}

df2 = pd.DataFrame(data=data, index=[1, 2, 3, 4])  # Note: index starts at 1

In [28]:
df2.iloc[1:3]  # position-oriented

   AAA  BBB  CCC
2    5   20   50
3    6   30  -30

In [29]:
df2.loc[1:3]  # label-oriented

   AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30

Using inverse operator (~) to take the complement of a mask.

In [30]:
df = pd.DataFrame(
    {
        "AAA": [4, 5, 6, 7],
        "BBB": [10, 20, 30, 40],
        "CCC": [100, 50, -30, -50],
    }
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [31]:
df[~((df.AAA <= 6) & (df.index.isin([0, 2, 4])))]

   AAA  BBB  CCC
1    5   20   50
3    7   40  -50

## New Columns
Efficiently and dynamically create new columns using DataFrame.map

In [32]:
df = pd.DataFrame(
    {
        "AAA": [1, 2, 1, 3],
        "BBB": [1, 1, 2, 2],
        "CCC": [2, 1, 3, 1],
    }
)
df

   AAA  BBB  CCC
0    1    1    2
1    2    1    1
2    1    2    3
3    3    2    1

In [33]:
source_cols = df.columns  # Or some subset would work too
new_cols = [str(x) + "_cat" for x in source_cols]
categories = {1: "Alpha", 2: "Beta", 3: "Charlie"}

df[new_cols] = df[source_cols].map(categories.get)
df

   AAA  BBB  CCC  AAA_cat BBB_cat  CCC_cat
0    1    1    2    Alpha   Alpha     Beta
1    2    1    1     Beta   Alpha    Alpha
2    1    2    3    Alpha    Beta  Charlie
3    3    2    1  Charlie    Beta    Alpha

Keep other columns when using min() with groupby

In [34]:
df = pd.DataFrame(
    {
        "AAA": [1, 1, 1, 2, 2, 2, 3, 3],
        "BBB": [2, 1, 3, 4, 5, 1, 2, 3],
    }
)
df

   AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [35]:
# METHOD 1: idxmin() to get the index of the minimums
df.loc[df.groupby("AAA")["BBB"].idxmin()]

   AAA  BBB
1    1    1
5    2    1
6    3    2

In [36]:
# METHOD 2: Sort, then take first of each
df.sort_values(by="BBB").groupby("AAA", as_index=False).first()

   AAA  BBB
0    1    1
1    2    1
2    3    2

# Multiindexing
Create a multiindex from a labeled frame

In [37]:
df = pd.DataFrame(
    {
        "row": [0, 1, 2],
        "One_X": [1.1, 1.1, 1.1],
        "One_Y": [1.2, 1.2, 1.2],
        "Two_X": [1.11, 1.11, 1.11],
        "Two_Y": [1.22, 1.22, 1.22],
    }
)
df

   row  One_X  One_Y  Two_X  Two_Y
0    0    1.1    1.2   1.11   1.22
1    1    1.1    1.2   1.11   1.22
2    2    1.1    1.2   1.11   1.22

In [38]:
# As Labeled Index
df = df.set_index("row")
df

     One_X  One_Y  Two_X  Two_Y
row
0      1.1    1.2   1.11   1.22
1      1.1    1.2   1.11   1.22
2      1.1    1.2   1.11   1.22

In [39]:
# With hierarchical columns
df.columns = pd.MultiIndex.from_tuples([tuple(c.split("_")) for c in df.columns])
df

     One        Two
       X    Y     X     Y
row
0    1.1  1.2  1.11  1.22
1    1.1  1.2  1.11  1.22
2    1.1  1.2  1.11  1.22

In [40]:
# Now stack & Reset
df = df.stack(level=0).reset_index()
df

   row level_1     X     Y
0    0     One  1.10  1.20
1    0     Two  1.11  1.22
2    1     One  1.10  1.20
3    1     Two  1.11  1.22
4    2     One  1.10  1.20
5    2     Two  1.11  1.22

## Arithmetic
Performing arithmetic with a MultiIndex that needs broadcasting

In [41]:
cols = pd.MultiIndex.from_tuples(
    [(x, y) for x in ["A", "B", "C"] for y in ["O", "I"]],
)

df = pd.DataFrame(
    np.random.randn(2, 6),
    index=["n", "m"],
    columns=cols,
)

df

          A                   B                   C
          O         I         O         I         O         I
n -0.911734  1.399371  0.663269 -0.238619 -1.159707 -0.919318
m  0.273422  2.819289 -0.935865  0.284969 -1.137717  1.781340

In [42]:
df = df.div(df["C"], level=1)
df

    A       B       C
    O   I   O   I   O   I
n NaN NaN NaN NaN NaN NaN
m NaN NaN NaN NaN NaN NaN

## Slicing
Slicing a MultiIndex with xs

In [43]:
coords = [("AA", "one"), ("AA", "six"), ("BB", "one"), ("BB", "two"), ("BB", "six")]
index = pd.MultiIndex.from_tuples(coords)
df = pd.DataFrame([11, 22, 33, 44, 55], index, ["MyData"])
df

        MyData
AA one      11
   six      22
BB one      33
   two      44
   six      55

In [44]:
# NOTE: level and axis are optional, and default to zero
# Cross section of the first index level and first axis
df.xs("BB", level=0, axis=0)

     MyData
one      33
two      44
six      55

In [45]:
# Cross section of the 2nd level of the 1st axis
df.xs("six", level=1, axis=0)

    MyData
AA      22
BB      55

Slicing a MultiIndex with xs, method #2

In [46]:
import itertools

index = list(itertools.product(["Ada", "Quinn", "Violet"], ["Comp", "Math", "Sci"]))
headr = list(itertools.product(["Exams", "Labs"], ["I", "II"]))
indx = pd.MultiIndex.from_tuples(index, names=["Student", "Course"])
cols = pd.MultiIndex.from_tuples(headr)
data = [[70 + x + y + (x * y) % 3 for x in range(4)] for y in range(9)]
df = pd.DataFrame(data, indx, cols)
print(df)

               Exams     Labs
                   I  II    I  II
Student Course
Ada     Comp      70  71   72  73
        Math      71  73   75  74
        Sci       72  75   75  75
Quinn   Comp      73  74   75  76
        Math      74  76   78  77
        Sci       75  78   78  78
Violet  Comp      76  77   78  79
        Math      77  79   81  80
        Sci       78  81   81  81

In [47]:
All = slice(None)

In [48]:
df.loc["Violet"]

       Exams     Labs
           I  II    I  II
Course
Comp      76  77   78  79
Math      77  79   81  80
Sci       78  81   81  81

In [49]:
df.loc[(All, "Math"), All]

               Exams     Labs
                   I  II    I  II
Student Course
Ada     Math      71  73   75  74
Quinn   Math      74  76   78  77
Violet  Math      77  79   81  80

## Sorting
Sort by specific column or an ordered list of columns, with a MultiIndex

In [51]:
df.sort_values(by=("Labs", "II"), ascending=False)

               Exams     Labs
                   I  II    I  II
Student Course
Violet  Sci       78  81   81  81
        Math      77  79   81  80
        Comp      76  77   78  79
Quinn   Sci       75  78   78  78
        Math      74  76   78  77
        Comp      73  74   75  76
Ada     Sci       72  75   75  75
        Math      71  73   75  74
        Comp      70  71   72  73

# Missing Data
Fill forward a reversed timeseries

In [54]:
df = pd.DataFrame(
    np.random.randn(6, 1),
    index=pd.date_range("2013-08-01", periods=6, freq="B"),
    columns=list("A"),
)

df.loc[df.index[3], "A"] = np.nan
df

                   A
2013-08-01  0.725559
2013-08-02  1.931557
2013-08-05  1.237831
2013-08-06       NaN
2013-08-07 -0.721311
2013-08-08  1.306050

In [55]:
df.bfill()

                   A
2013-08-01  0.725559
2013-08-02  1.931557
2013-08-05  1.237831
2013-08-06 -0.721311
2013-08-07 -0.721311
2013-08-08  1.306050

# Grouping
Basic grouping with apply

In [57]:
df = pd.DataFrame(
    {
        "animal": "cat dog cat fish dog cat cat".split(),
        "size": list("SSMMMLL"),
        "weight": [8, 10, 11, 1, 20, 12, 12],
        "adult": [False] * 5 + [True] * 2,
    }
)
df

  animal size  weight  adult
0    cat    S       8  False
1    dog    S      10  False
2    cat    M      11  False
3   fish    M       1  False
4    dog    M      20  False
5    cat    L      12   True
6    cat    L      12   True

In [59]:
# List the size of the animals with the highest weight
df.groupby("animal").apply(lambda subf: subf["size"][subf["weight"].idxmax()])

animal
cat     L
dog     M
fish    M
dtype: str

In [60]:
gb = df.groupby("animal")

gb.get_group("cat")

  animal size  weight  adult
0    cat    S       8  False
2    cat    M      11  False
5    cat    L      12   True
6    cat    L      12   True

Apply to different items in a group

In [62]:
def GrowUp(x):
    avg_weight = sum(x[x["size"] == "S"].weight * 1.5)

    return pd.Series(["L", avg_weight, True], index=["size", "weight", "adult"])


expected_df = gb.apply(GrowUp)
expected_df

       size  weight  adult
animal
cat       L    12.0   True
dog       L    15.0   True
fish      L     0.0   True